### ISSUE TITLE
Critical error while updating media items

### ISSUE THREAD

**Issue by kevinbrechbuehl** [SitecoreUnicorn/Unicorn#21]
Hi Kam

We have an error with Unicorn 2 in the media library. For this example I have the whole media library serialized:

```
<include database="master" path="/sitecore/media library"/>
```

When I add a file (i.e. an image) to the media library it seems to work and the item is serialized. But when I want to save the item again without changing the blob (i.e. changing the alt-text of my image), I always get the following error message as browser popup (here in chrome):

![save_image](https://cloud.githubusercontent.com/assets/1330775/2665056/c89ed6d0-c087-11e3-949d-a3b61e954c36.png)

It doesn't matter if I sync the database exactly before I change the alt-text and save the image item, the error message is always shown. I have tested this on a clean Sitecore 7.2 (rev. 140314).

Can you reproduce this or am I doing something wrong? Or what be the cause of this? When I interpret the error message correctly it says that the blob has changed...

**Comment by massisalerno** [comment]
Dear @kamsar ,
I have the same error today with __Semantics field (Tagging section). I have a custom field to browse tagging, then when I save I try to set the __Semantics field programmatically. It works for the first or second attempt then I have the same modal error. Is there a way to avoid or solve it?
![unicornerror](https://user-images.githubusercontent.com/33760243/32960797-8d103db8-cbc6-11e7-962b-074bea0b64e4.jpg)
