### ISSUE TITLE
Unable to 'unlink' file 'tools/PSAPI/MicroCHAP.dll'

### ISSUE THREAD

**Issue by sergeyshushlyapin** [SitecoreUnicorn/Unicorn#248]
I'm configuring [Unicorn Automated Tool API](https://github.com/kamsar/Unicorn/blob/ab7ff36335c6cf537a253e8f3525b67e65716030/README.md#use-the-automated-tool-api). I use `Sync-Unicorn` cmdlet and it works fine except one thing. The command locks the `MicroCHAP.dll` file so that it cannot be removed until I close the console.

For instance, when I try to switch to another branch that does not contain the `MicroCHAP.dll` I receive the following error:
```
Unlink of file 'build/tools/PSAPI/MicroCHAP.dll' failed. Should I try again? (y/n)
```

Sitecore 8.2.4, Unicorn 4.0.2

**Comment by kamsar** [comment]
Unfortunately that's a powershell thing when it loads an assembly. It's
pretty greedy about holding on to them until the console is closed.

I tend to use scripts that execute powershell.exe explicitly thus
terminating the session and avoiding the locking.

**Comment by bii** [comment]
I had the same issue. Try syncing in a new process. Something like this

Start-Process -FilePath "powershell.exe" -ArgumentList "..\unicorn\Unicorn.ps1 $($instanceUrl + "/unicorn.aspx") $secret" -Wait -PassThru -NoNewWindow -Verbose

**Comment by kamsar** [comment]
This might also be a reasonable workaround http://ogresoft.blogspot.com/2011/08/powershell-locks-loaded-assemblies.html

**Comment by cassidydotdk** [comment]
Not much that can be done from inside the project, this is broader behaviour around PS - with various workarounds possible
