### ISSUE TITLE
Auto Publish ends in middle of publishing

### ISSUE THREAD

**Issue by aleksandartraja** [SitecoreUnicorn/Unicorn#253]
We are using Sitecore 8.2 update 3 with unicorn 4.0

We are deploying on azure env
We have three regions North europe, East Us and East asia

The syncing part everything is ok, but when it comes to publish we have issues.

reallog.txt show us that the publishing ends when the second region is affected (webeastus), the first one is web(northeurope), the third one doesnt even get to publishing.

The desiredlog.txt shows what we want to achieve, how the publish should look a like.

This scenario only happens when we run the Unicorn.psm1 in VSTS, while using the UI of Unicorn is not a problem.

Attached are the reallog.txt, desiredlog.txt, Unicorn.psm1, Unicorn.AutoPublish.config.

If you need further details please ping me

[desiredlog.txt](https://github.com/kamsar/Unicorn/files/1428043/desiredlog.txt)
[reallog.txt](https://github.com/kamsar/Unicorn/files/1428044/reallog.txt)
[Unicorn.AutoPublish.config.txt](https://github.com/kamsar/Unicorn/files/1428045/Unicorn.AutoPublish.config.txt)
[Unicorn.psm1.txt](https://github.com/kamsar/Unicorn/files/1428046/Unicorn.psm1.txt)

**Comment by kamsar** [comment]
The relevant code that does the publish is here: https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/Publishing/ManualPublishQueueHandler.cs

The logs (which look like they're from VSTS) look like the process is ending before it's done, as you surmised. Have you reviewed the Sitecore logs? Unicorn writes its information there as well, and in case an exception or something occurred, those may have the missing pieces we need to diagnose this.

**Comment by aleksandartraja** [comment]
![image](https://user-images.githubusercontent.com/1612972/33833365-b3bd70b8-de7f-11e7-9910-f10ac7ed6be4.png)

**Comment by aleksandartraja** [comment]
Kam, we have interesting findings, and we want to present to you, offline this thread if that is ok by you. Please contact me on aleksandar.trajanovski@outlook.com.

**Comment by kamsar** [comment]
Community slack would be a good venue. Send me a DM there, please. 




On Fri, Feb 16, 2018 at 3:25 AM -0800, "aleksandartraja" <notifications@github.com> wrote:












Kam, we have interesting findings, and we want to present to you, offline this thread if that is ok by you. Please contact me on aleksandar.trajanovski@outlook.com.

**Comment by cassidydotdk** [comment]
Has this been resolved offline?
