### ISSUE TITLE
Auto publish in the end does not seem to work with Sitecore's new publishing server

### ISSUE THREAD

**Issue by melker** [SitecoreUnicorn/Unicorn#256]
Sitecore 8.2, Unicorn 4.0.1, Publishing server 2.0 update 1 (will soon upgrade to 2.1)

The auto publish run in the end does not seem too work with the new Publishing Server from Sitecore.
https://dev.sitecore.net/Downloads/Sitecore_Publishing_Service.aspx
Unicorn says it is published but it is actually not published.

Before we installed the publishing service it seemed to work but now we have to publish it manually.
Is there some setting we have to adjust, is it something that not has been implemented yet or simply a bug?

**Comment by kamsar** [comment]
I'm not too familiar with how Publishing Service's APIs work, but I vaguely recall that it doesn't do incremental publishing (which is how Unicorn's auto publish works). It may make sense, if using publishing service, to trigger a smart publish instead. I'll poke at the APIs when I get a chance, but it may be a bit.

**Comment by kamsar** [comment]
Are you using transparent sync for your items? If so, publishing service won't see them. You'll want to make sure that items are being synced into the database proper (explicitly sync those configurations; by default the UI may skip them) so that the auto publish can pick them up.

**Comment by melker** [comment]
We are not using transparent sync (I had to lookup what it is, first).

I can't really tell if the publishing service is using the incremental publishing the same way. It is very simplified in the user interface as you probably know, it does not have the user interface setting for running incremental. What I can tell is that it is not using the same workflows at least.

**Comment by taulantracaj** [comment]
Hi Kamsar,

I see that here you have discussed about publishing service.

Is there any update on how unicorn would use this publishing service for the auto publish?

I setup publishing service but when I do unicorn sync it does not use publishing service for publishing service.

**Comment by cassidydotdk** [comment]
This has been included in https://github.com/SitecoreUnicorn/Unicorn/releases/tag/4.1.2-pre8

**Comment by cassidydotdk** [comment]
(better late than never ;-))
