### ISSUE TITLE
Unicorn Sync does not delete items from Sitecore

### ISSUE THREAD

**Issue by navneet-keshav** [SitecoreUnicorn/Unicorn#259]
Scenario: I deleted one item from Sitecore, it deleted YML file from unicorn folder. I checked in to the repository (Git). One of my colleagues took latest. It deleted YML file from unicorn folder on his PC. Once he tried to SYNC using Unicorn.aspx, it did not delete that item from Sitecore. New items creation and update in existing items work correctly.

**Unicorn.config:**
![image](https://user-images.githubusercontent.com/32305943/33093367-cf1ae7a6-ceca-11e7-8a95-a1df2634d53e.png)

If I change it like given below, delete works correctly. 
![image](https://user-images.githubusercontent.com/32305943/33093498-1db7ea62-cecb-11e7-9ec4-150d0675222f.png)

INCLUDE, EXCLUDE and EXCEPT are working for adding and updating items in Siteore but not deleting while Unicorn SYNC. Thoughts/Comments?

Thanks,
Navneet Keshav

**Comment by kamsar** [comment]
Which evaluator is being used?

**Comment by navneet-keshav** [comment]
<evaluator type="Unicorn.Evaluators.SerializedAsMasterEvaluator, Unicorn" singleInstance="true"/>

**Comment by navneet-keshav** [comment]
Hi, any update?

**Comment by kamsar** [comment]
It's possible that it's a bug. At the moment, I'm waiting on a license that I can officially use to maintain my OSS projects (it's in process) so I can't check it. I would suggest referencing Unicorn from source (pretty easy to do, all the dependencies are from NuGet) and debugging in the meantime. Feel free to ask questions on #unicorn in community slack if you need help getting set up.

**Comment by navneet-keshav** [comment]
Sure. I'll look at it.

**Comment by cassidydotdk** [comment]
A number of fixes were done that will be released in 4.0.4 having to do with EnforceVersionPresence. I'm assuming this problem will be resolved by this.
