### ISSUE TITLE
Ability to specify a wildcard for the configuration names when using PowerShell API Sync

### ISSUE THREAD

**Issue by michaellwest** [SitecoreUnicorn/Unicorn#279]
In the current version of Unicorn, 4.0, I'm unable to do the following when performing a sync using the PowerShell API:

* Specify a configuration name using lowercase
* Specify a wildcard for configuration names

**Example:** The following would allow me to be even more lazy.

```powershell
Sync-Unicorn -ControlPanelUrl "https://int.companyname.com/unicorn.aspx" `
-SharedSecret 'TOO_SECURE_TO_SHOW' -Configurations @("companyname.*")
```

**Comment by kamsar** [comment]
This would also go well with #241

**Comment by cassidydotdk** [comment]
Lowercasing configuration names would be a broader change. Wildcarding configuration names however, can be done without breakage and spillage ;-)
