### ISSUE TITLE
When not logged into Sitecore, Unicorn no longer presents the "You must log in" page on Sitecore 9

### ISSUE THREAD

**Issue by cassidydotdk** [SitecoreUnicorn/Unicorn#287]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Opening a new browser session and navigating to /unicorn.aspx is supposed to present you with an Access Denied custom page, with a link to /sitecore/admin/login.aspx.  On Sitecore 9, this fails.

![image](https://user-images.githubusercontent.com/8483909/40166954-11dbac3a-59c0-11e8-9aa5-59a0c537f8ff.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
As above

**What is the expected behavior?**
The proper Access Denied page from Unicorn Control Panel is presented.

![image](https://user-images.githubusercontent.com/8483909/40166997-2dc60dfa-59c0-11e8-945e-e612279800dd.png)

**Please mention your Sitecore version and Unicorn version.**
Unicirn 4.0.3 and Sitecore 9.0u1

**Comment by mmacehardyman** [comment]
@cassidydotdk Why is this issue closed? Not a Unicorn issue after all? And if not, what was the cause? Did you manage to figure this out?

**Comment by cassidydotdk** [comment]
Yep, it's solved. Sitecore 9 reacts differently than 8, when the Unicorn.aspx "page" returned 401.

**Comment by mmacehardyman** [comment]
Check, I overlooked that it has a commit id attached with this fix in it. I thought the issue was just closed without providing a fix or a comment.

Nicely done! :)

**Comment by mmacehardyman** [comment]
By they way, when will this fix (and all the fixes made lately) be released as a new version (4.04?).

**Comment by cassidydotdk** [comment]
4.0.4 ultimately. But will likely do a pre-release sometime this or next week.
