### ISSUE TITLE
Sync-Unicorn : Exception calling "GetResponse" (401) Unauthorized

### ISSUE THREAD

**Issue by csoler46** [SitecoreUnicorn/Unicorn#290]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

Hi Community,

In one of our environements, we are having an issue when trying to syncronize our Unicorn items using a powershell script (using the modules in Unicorn.psm1).

The error that we are receiving is:

`Sync-Unicorn : Exception calling "GetResponse" with "0" argument(s): "The 
Error remote server returned an error: (401) Unauthorized."`

And in our application logs we can see this error:

`WARN  [Unicorn-Auth] CHAP challenge store rejected Pre Get Challenge  POST Get Challenge 3f7557c254cd4f3e9ad455df390b6aba because it was unknown.`

The error is thrown in (Unicorn.psm1) this point of the execution:

Write-Host "Sync-Unicorn: Executing $Verb..."

	# USING THE SIGNATURE, EXECUTE UNICORN
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
	$result = Invoke-StreamingWebRequest -Uri $url -Mac $signature.SignatureHash -Nonce $challenge

The script had been working fine the last four weeks in all the environements. However on a specific environement this is not working (that means that the script should be ok). Unfortunately, we don't have completely under source control/scripted the installation of our virtual machines/IIS... so it could be that there are configuration differences between environements

We have verified and the SharedSecret parameter is fine (in Unicorn.Ui.config and also the one provided as a parameter in the script)

Any clue on what should we check to make it working? We had been struggling a lot of time with this issue without success. In case you need more information don't hesitate in asking!

Thanks in advance!

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute the powershell script to syncronize items:

> Sync-Unicorn -ControlPanelUrl $syncUnicornUrl -Configurations $configurations -SharedSecret $SharedSecret -DebugSecurity

**What is the expected behavior?**
A good syncronization
**Please mention your Sitecore version and Unicorn version.**
Sitecore 8.0
Unicorn 4.0.3

**Comment by omcbride** [comment]
I am experiencing the exact same issue that was described above. Did anyone ever find a solution to this?
