### ISSUE TITLE
Error message when trying to install Unicorn

### ISSUE THREAD

**Issue by JayValen** [SitecoreUnicorn/Unicorn#291]
What is the current behavior?
Error message: dotnet : Could not find any project in 'C:\Users\"User Name"\'.

If the current behavior is a bug, please provide the steps to reproduce.
In Visual Studio 2017 I first: 

- Clicked on Tools
- Selected NuGet Package Manager -> Package Manager Console
- Inserted code after PM> **dotnet add package unicorn --version 4.0.3**
- Error message: 
dotnet : Could not find any project in 'C:\Users\"User Name"\'.
At line:1 char:1
+ donet add package Unicorn --version 4.0.3
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (Could not find ...rs\"User Name"\'.:String) [], RemoteException
+FullyQualifiedErrorId : NativeCommandError

**Please mention your Sitecore version and Unicorn version.**
Sitecore Version 7.0 and Unicorn Version 4.0.3

**Comment by kamsar** [comment]
`dotnet add` is only for .NET Core projects. Sitecore (and Unicorn) require the full .NET Framework.

the `Install-Package` cmdlet is the PM console equivalent.

...also Unicorn 4 does not support Sitecore 7.0. You'd need to use an older version.
