### ISSUE TITLE
Sitecore content tree broken when transparent sync enabled

### ISSUE THREAD

**Issue by tomunderhill** [SitecoreUnicorn/Unicorn#292]
I'm having an issue with Unicorn 4.0.3.
Sitecore 7.0 (rev. 140408)

When I have Transparent Sync enabled, the Sitecore tree is missing most of it's content. Only the top level, or second level items show but all further children are missing. So I can see /sitecore/content/Home, but nothing below this.

If I right-click and do "Refresh", then I can see the children are still there. But if I collapse the parent and re-open, the children are missing again.

If I disable Transparent Sync, the tree shows fine with the same Unicorn config.

**Comment by kamsar** [comment]
Unicorn 4 does not support Sitecore 7.0. You'd need to use an older version.
________________________________

**Comment by tomunderhill** [comment]
Ah ok, thanks, got it. Is there a table somewhere of which versions of Sitecore match up to which of Unicorn?

**Comment by tomunderhill** [comment]
3.3.2 has the same issue as far as I can see

**Comment by cassidydotdk** [comment]
Anything showing up in logs or anywhere else, that might help zeroing in on this?

**Comment by tomunderhill** [comment]
I'm afraid not, not in the Sitecore logs anyway. There don't seem to be client side js errors either. 

We're getting on without Transparent Sync for the moment. I'd have been happy to downgrade to 3.3.2, but as I say that doesn't seem to fix it.

**Comment by cassidydotdk** [comment]
Ok. I'll got down to the basement then and dust off a 7.0 install. Will try putting a debugger on it, see what comes up :-)
