### ISSUE TITLE
Sync only specific fields on configuration level

### ISSUE THREAD

**Issue by hombreDelPez** [SitecoreUnicorn/Unicorn#305]
**Do you want to request a *feature* or report a *bug*?**
Feature respectively question.

**What is the current behavior?**
1.) According to the Unicorn documentation it is currently not possible to overwrite the fieldFilter on configuration level (i.e. just for a specific configuration):

![image](https://user-images.githubusercontent.com/20950007/44081040-106baa1a-9fae-11e8-8dbc-cb9cd00c8be4.png)
https://kamsar.net/index.php/2017/02/Unicorn-4-Part-III-Configuration-Enhancements/

 2.) And I'm not sure if it's possible to define includes. The *Unicorn.config* which is delivered with the NuGet comes with excludes children in the *fieldFilter* node:

![image](https://user-images.githubusercontent.com/20950007/44081270-9bf6c9f2-9fae-11e8-9c4d-8953c5484736.png)

**What is the expected behavior?**
So are the two features mentioned above possible with Unicorn 4.0.4 and if not, is it planned to implement these in a future version?

**Please mention your Sitecore version and Unicorn version.**
Sitecore 9.0.2 and Unicorn 4.0.3

Kind regards
Manuel

**Comment by kamsar** [comment]
You can override the field filter per config. What you cannot do is extend the base filter set, it must be redefined using the 'type' attribute.
________________________________

**Comment by cassidydotdk** [comment]
What problem is it, you're trying to solve here?  It isn't immediately obvious to me

**Comment by hombreDelPez** [comment]
@kamsar 
I tested it with a new configuration and defined a new _fieldFilter_ there:

```xml
<configuration name="TestConfig" description="Test configuration for just syncing the Security field">					   
	<fieldFilter type="Rainbow.Filtering.ConfigurationFieldFilter, Rainbow" singleInstance="true">
		<include fieldID="{DEC8D2D5-E3CF-48B6-A653-8E69E2716641}" note="'Security' field on Standard Template" />
	</fieldFilter>
	<predicate type="Unicorn.Predicates.SerializationPresetPredicate, Unicorn" singleInstance="true">
		<include name="Settings Item" database="master" path="/sitecore/system/Settings" >
			<exclude children="true" />
		</include>					
	</predicate>				
</configuration>
```
Unfortunately it doesn't just sync the _Security_ field. So I'm not sure if my configuration is wrong or if this is just not possible.

@cassidydotdk 
In one of our projets we have the situation that the customer is administering the access rights himself and commits it via TDS to our git repo. Now we are switching to Unicorn (because it makes the deployment simpler) and now my idea was to create a distinct Unicorn config just for standard Sitecore items with custom access rights. So it would be a cool feature to just sync the _Security_ field. This would make a future Sitecore upgrade a bit easier.

I will be on vacation the new few weeks with no access to a dev machine so it won't be possible for me to respond here.

**Comment by cassidydotdk** [comment]
The default configuration filter - `Rainbow.Filtering.ConfigurationFieldFilter` is "only" a filter. Meaning you can only use it to filter out fields, not "include" fields again. As such, you cannot do an "exclude all fields" and then include "security" back in.

It would be reasonably trivial to set up a custom filter that could achieve this however.  Look how little code is actually in the built-in filter:

https://github.com/SitecoreUnicorn/Rainbow/blob/master/src/Rainbow/Filtering/ConfigurationFieldFilter.cs

**Comment by koga73** [comment]
> You can override the field filter per config. What you cannot do is extend the base filter set, it must be redefined using the 'type' attribute.

When you say you can only override fieldFilter and not extend it, does that mean in my project's serialization.config I need to copy the default field filters (__Owner, __Revision, __Updated, etc) from the base unicorn.config into my local serialization.config to ensure these fields remain excluded?

**Comment by kamsar** [comment]
Yes
________________________________
