### ISSUE TITLE
Configuration(s) requested were not defined.

### ISSUE THREAD

**Issue by bardawilpeter** [SitecoreUnicorn/Unicorn#306]
I am getting the below error while running:
http://siteurl.com/unicorn.aspx?verb=Sync&configuration=&skipTransparentConfigs=0

Configuration(s) requested were not defined.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
Exception Details: System.ArgumentException: Configuration(s) requested were not defined.
Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--
Stack Trace: 
[ArgumentException: Configuration(s) requested were not defined.]
   Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.SyncVerb.ResolveConfigurations() +430
   Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.SyncVerb.Process(IProgressStatus progress, ILogger additionalLogger) +28
   Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.<>c__DisplayClass3_0.<CreateResponse>b__0(IProgressStatus progress) +175
   Unicorn.ControlPanel.Responses.WebConsoleResponse.ProcessInternal(IProgressStatus progress) +498
   Kamsar.WebConsole.Html5WebConsole.Render(Action`1 processAction) +283
   Unicorn.ControlPanel.UnicornControlPanelPipelineProcessor.ProcessRequest(HttpContext context) +710
   Unicorn.ControlPanel.UnicornControlPanelPipelineProcessor.Process(HttpRequestArgs args) +110
   (Object , Object ) +14
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +236
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22
   Sitecore.Web.RequestEventsHandler.OnPostAuthenticateRequest(HttpContextBase context) +214
   Sitecore.Nexus.Web.HttpModule.(Object , EventArgs ) +335
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +223
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +213
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +91

**Comment by cassidydotdk** [comment]
Which version are you on?

**Comment by peterbardawil** [comment]
i am using Sitecore 9.0.2

**Comment by cassidydotdk** [comment]
... of Unicorn

**Comment by peterbardawil** [comment]
Unicorn 4.0.3 and it's working on habitat project locally bu after i pushed to Azure server i am getting this error

**Comment by cassidydotdk** [comment]
Looks to me like you've not pushed all the configurations out. There's nothing wrong with your URL so if it ends up with "no configurations defined" it means there are no configurations at all

**Comment by peterbardawil** [comment]
yes you were right there a missing config but now i am getting Access to the path 'C:\projects\Habitat\src\Feature\Accounts\serialization' is denied.

**Comment by bardawilpeter** [comment]
yes you were right a config were missing thanks for the help but now i am getting Access to the path 'C:\projects\Habitat\src\Feature\Accounts\serialization' is denied. i think i should alter a habitat config

**Comment by cassidydotdk** [comment]
Well there would be no `C:\` drive on your Azure installation. I suggest you connect with the Sitecore Community on our public Slack offering and check with people in the #azure channel on how to set up your deployment and configuration transformation correctly.

If you're not a member already, here is the sign-up link: https://bit.ly/SitecoreSlack

**Comment by bardawilpeter** [comment]
@cassidydotdk Thank a lot for your help

**Comment by suravaram** [comment]
> yes you were right a config were missing thanks for the help but now i am getting Access to the path 'C:\projects\Habitat\src\Feature\Accounts\serialization' is denied. i think i should alter a habitat config

can you please tell me what config did you miss. i am getting the same error.
