### ISSUE TITLE
Unicorn is not creating root predicate under sitecore tree

### ISSUE THREAD

**Issue by peterbardawil** [SitecoreUnicorn/Unicorn#307]
Trying to run unicorn sync with the following link "https://mysite.com/unicorn.aspx?verb=Sync&configuration=&skipTransparentConfigs=0" to sync the habitat project serialized file and note that all the config files with all the predicates alll already defined but not being created under sitecore tree any help i am always getting the below and the serialized items are not being created because the root predicate doesn't exist. Please check the below:

**Warning: your current predicate configuration for at least one configuration does not have any valid root items defined. Nothing will be serialized until valid root items to start serializing from can be resolved. Please review your predicate configuration.**

And Another Exception when trying to sync:
Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException' was thrown

**Comment by cassidydotdk** [comment]
You're missing some root items. As it says. Likely `Foundation`, `Feature` and `Project`. Double check the configs you have defined; there would be some Habitat base configs that appear to be missing.

This is really an issue for the Habitat project.
