### ISSUE TITLE
Update Kamsar.WebConsole and Rainbow Dependencies

### ISSUE THREAD

**Issue by coreyasmith** [SitecoreUnicorn/Unicorn#309]
**Do you want to request a *feature* or report a *bug*?**
Bug (feature?)

**What is the current behavior?**
The latest version of the `Unicorn` NuGet package installs version `2.0.0` of `Kamsar.WebConsole` and version `2.0.1` of `Rainbow`, but `2.0.1` and `2.0.2` are the latest versions, respectively.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install the latest Unicorn NuGet package. You will need to install 5 updates: one for `Kamsar.WebConsole`, and four for `Rainbow`.

**What is the expected behavior?**
The latest version of the `Unicorn` NuGet package installs version `2.0.1` of `Kamsar.WebConsole` and version `2.0.2` of the `Rainbow` NuGet packages so that no updates are required after installing it.

**Please mention your Sitecore version and Unicorn version.**
- Sitecore: `9.0.2`
- Unicorn: `4.0.4`

**Comment by coreyasmith** [comment]
Looks like `Rainbow` versions will have to be updated next time the `Unicorn` NuGet packages are generated.

**Comment by cassidydotdk** [comment]
`Rainbow` dependency will be updated on `Unicorn` when it is required :-)

`Unicorn` 4.0.4 only needs `Rainbow` 2.0.0.  The only changes to Rainbow in 2.0.1 was the introduction of some Language Fallback and EnforceVersionPresence handling - which broke it's compatibility with any Sitecore version below 8.1 (or so - whenever enforce version presence was introduced). Then Rainbow 2.0.2 was released a short while after, where this had been implemented in a more compatible manner.

None of this matters for `Unicorn` however, as in 4.0.4 it ensures that it executes in a site context where these features (fallback, version forcing) are disabled.

`Rainbow` > 2.0.0 is currently only needed by projects that use it outside a Unicorn context. Like Sidekick.

**Comment by coreyasmith** [comment]
Makes sense to me. Just found out that you can control this in the client so that the latest version of all dependencies are automatically installed. Works great.

![image](https://user-images.githubusercontent.com/6156761/44946844-cf26d980-add1-11e8-9032-efc404d777ae.png)
