### ISSUE TITLE
Role predicate type doesn't get loaded and causes ysod when adding role sync configs

### ISSUE THREAD

**Issue by vasiliyfomichev** [SitecoreUnicorn/Unicorn#313]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Sitecore 9.0.2 with SXC 9.0.2 
Created an empty VS 2017 web solution and added Unicorn and Unicorn Roles 4.0.4 packages from nuget. Was able to create content sync predicates, however, when trying to add role predicate, a ysod comes up complaining that there are no include items ("No include entries were present on the predicate for..."). Looked like it was falling through to the default predicate parser; set that to the role one and now getting "The expected type Unicorn.Predicates.IPredicate was not registered with the container."

stack for no includes - 

[InvalidOperationException: No include entries were present on the predicate for the JoyceMeyer Security Roles Unicorn configuration. You must explicitly specify the items you want to include.]    Unicorn.Predicates.SerializationPresetPredicate.EnsureEntriesExist(String configurationName) +107    Unicorn.Predicates.SerializationPresetPredicate..ctor(XmlNode configNode, IUnicornDataProviderConfiguration dataProviderConfiguration, IConfiguration configuration) +128    lambda_method(Closure , Object[] ) +187    Configy.Containers.MicroContainer.Activate(Type type, KeyValuePair`2[] unmappedConstructorParameters) +880    System.Lazy`1.CreateValue() +236    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31    System.Lazy`1.get_Value() +14627129    Configy.Containers.MicroContainer.Resolve(Type type) +59    Configy.Containers.MicroContainer.Activate(Type type, KeyValuePair`2[] unmappedConstructorParameters) +405    Configy.Containers.MicroContainer.Resolve() +110    System.Linq.WhereSelectArrayIterator`2.MoveNext() +145    System.Linq.Buffer`1..ctor(IEnumerable`1 source) +281    System.Linq.Enumerable.ToArray(IEnumerable`1 source) +90    Unicorn.Data.DataProvider.UnicornSqlServerDataProvider..ctor(String connectionString) +219  [TargetInvocationException: Exception has been thrown by the target of an invocation.]    System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0    System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +217    Sitecore.Reflection.ReflectionUtil.CreateObject(Type type, Object[] parameters) +119    Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +108    Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +163    Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72    Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert) +697    Sitecore.Configuration.DefaultFactory.CreateFromReference(XmlNode configNode, String[] parameters, Boolean assert) +170    Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +116    Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72    Sitecore.Configuration.DefaultFactory.GetInnerObject(XmlNode paramNode, String[] parameters, Boolean assert) +941    Sitecore.Configuration.DefaultFactory.AssignProperties(XmlNode configNode, String[] parameters, Object obj, Boolean assert, Boolean deferred, IFactoryHelper helper) +527    Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +320    Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72    Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert) +697    Sitecore.Configuration.DefaultFactory.GetDatabase(String name, Boolean assert) +157    Sitecore.Configuration.DefaultFactory.GetDatabase(String name) +55    Sitecore.Configuration.DefaultFactory.GetDatabases() +121    Sitecore.Data.Managers.DefaultItemManager.Initialize() +101    (Object , Object ) +87    Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484    (Object , Object ) +9    Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484    Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +236    Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22    Sitecore.Nexus.Web.HttpModule.Application_Start() +161    Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +767    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +581    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369  [HttpException (0x80004005): Exception has been thrown by the target of an invocation.]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +714
--

Stack for ipredicate not registered - 

[InvalidOperationException: The expected type Unicorn.Predicates.IPredicate was not registered with the container.]
   Configy.Containers.MicroContainer.Assert(Type type) +141
   Unicorn.Configuration.ConfigyConfigurationProvider.LoadConfigurations() +677
   Unicorn.Configuration.ConfigyConfigurationProvider.get_Configurations() +28
   Unicorn.Data.DataProvider.UnicornSqlServerDataProvider..ctor(String connectionString) +62

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +217
   Sitecore.Reflection.ReflectionUtil.CreateObject(Type type, Object[] parameters) +119
   Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +108
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +163
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72
   Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert) +697
   Sitecore.Configuration.DefaultFactory.CreateFromReference(XmlNode configNode, String[] parameters, Boolean assert) +170
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +116
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72
   Sitecore.Configuration.DefaultFactory.GetInnerObject(XmlNode paramNode, String[] parameters, Boolean assert) +941
   Sitecore.Configuration.DefaultFactory.AssignProperties(XmlNode configNode, String[] parameters, Object obj, Boolean assert, Boolean deferred, IFactoryHelper helper) +527
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +320
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72
   Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert) +697
   Sitecore.Configuration.DefaultFactory.GetDatabase(String name, Boolean assert) +157
   Sitecore.Configuration.DefaultFactory.GetDatabase(String name) +55
   Sitecore.Configuration.DefaultFactory.GetDatabases() +121
   Sitecore.Data.Managers.DefaultItemManager.Initialize() +101
   (Object , Object ) +87
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   (Object , Object ) +9
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +236
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22
   Sitecore.Nexus.Web.HttpModule.Application_Start() +161
   Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +767
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +581
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +714

**If the current behavior is a bug, please provide the steps to reproduce.**
see above

**What is the expected behavior?**
no ysod :)

**Please mention your Sitecore version and Unicorn version.**

see above

**Comment by kamsar** [comment]
https://github.com/SitecoreUnicorn/Unicorn/blob/047f6f6c10cf9742ace015e360f4c8126ca4498e/src/Unicorn.Roles/Standard%20Config%20Files/Unicorn.Configs.Default.Roles.config.example#L29

**Comment by vasiliyfomichev** [comment]
Very cool! Commenting that one worked. Can that be documented, or have it uncommented by default? Thanks for a quick reply, man!
