### ISSUE TITLE
Unable to Sync parent item when using excludes to cherry pick children. 

### ISSUE THREAD

**Issue by AdamHess** [SitecoreUnicorn/Unicorn#321]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Unable to Sync items because parent items are missing from file system, even though parent items are serialized to the file system.

**If the current behavior is a bug, please provide the steps to reproduce.**

Given a tree with the following structure: 

/sitecore/Content/Example
/Sitecore/Content/Example/Configuration
/sitecore/content/Example/Configuration/Alert Types
/sitecore/content/Example/Configuration/Event Categories
/sitecore/Content/Example/Configuration/[dozens of other children]

and the following configuration

```
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
  <sitecore>
    <unicorn>
      <configurations>
        <configuration name="Example.Project.Website" >
          <targetDataStore physicalRootPath="$(sourceFolder)\project\website\serialization" type="Rainbow.Storage.SerializationFileSystemDataStore, Rainbow" useDataCache="false" singleInstance="true" />
          <predicate type="Unicorn.Predicates.SerializationPresetPredicate, Unicorn" singleInstance="true">
            <!--Development Site Structure Serialization-->
            <include name="Example.Project.Website.Scaffold" database="master" path="/sitecore/Content/Example">
              <exclude children="false">                            
                <except name="Configuration" includeChildren="false"/>
                <except name="Configuration/Alert Types" includeChildren="true" />
                <except name="Configuration/Event Categories" includeChildren="false"/>
            </include>
          </predicate>
        </configuration>
      </configurations>
    </unicorn>
  </sitecore>
</configuration>
```
When the items are Serialized to the file system the "Example" node appears in the file system, however when syncing the items back into the sitecore database Unicorn reports:

> Unable to resolve serialized item for included root path master:/sitecore/Content/Example. The item does not exist in Serialization File System Data Store. It has been skipped. Perhaps you need to perform an initial serialization from the control panel?

**What is the expected behavior?**

Sync should load in the parent item into the file system. 

This will work only if the parent item is present already in the content tree. 

**Please mention your Sitecore version and Unicorn version.**

9.0.2 and 4.0.4

**Comment by cassidydotdk** [comment]
The enclosed configuration is invalid XML. Testing with what I _think_ is the one you intended.

**Comment by cassidydotdk** [comment]
Serialized structure

```
 Directory of C:\inetpub\wwwroot\sc901\Data\Unicorn\Example.Project.Website

11/12/2018  17:58    <DIR>          .
11/12/2018  17:58    <DIR>          ..
11/12/2018  17:58    <DIR>          Example.Project.Website.Scaffold
               0 File(s)              0 bytes

 Directory of C:\inetpub\wwwroot\sc901\Data\Unicorn\Example.Project.Website\Example.Project.Website.Scaffold

11/12/2018  17:58    <DIR>          .
11/12/2018  17:58    <DIR>          ..
11/12/2018  17:58    <DIR>          Example
11/12/2018  17:58               485 Example.yml
               1 File(s)            485 bytes

 Directory of C:\inetpub\wwwroot\sc901\Data\Unicorn\Example.Project.Website\Example.Project.Website.Scaffold\Example

11/12/2018  17:58    <DIR>          .
11/12/2018  17:58    <DIR>          ..
11/12/2018  17:58    <DIR>          Configuration
11/12/2018  17:58               499 Configuration.yml
               1 File(s)            499 bytes

 Directory of C:\inetpub\wwwroot\sc901\Data\Unicorn\Example.Project.Website\Example.Project.Website.Scaffold\Example\Configuration

11/12/2018  17:58    <DIR>          .
11/12/2018  17:58    <DIR>          ..
11/12/2018  17:58               511 Alert Types.yml
11/12/2018  17:58               516 Event Categories.yml
               2 File(s)          1,027 bytes

     Total Files Listed:
               4 File(s)          2,011 bytes
              11 Dir(s)  423,515,869,184 bytes free

C:\inetpub\wwwroot\sc901\Data\Unicorn\Example.Project.Website>
```

**Comment by cassidydotdk** [comment]
Backup copy

![image](https://user-images.githubusercontent.com/8483909/49816765-dfeed000-fd6e-11e8-9eca-008579e3c7d7.png)

**Comment by cassidydotdk** [comment]
Deleting from Sitecore

![image](https://user-images.githubusercontent.com/8483909/49816803-f7c65400-fd6e-11e8-9aea-34b21cf125aa.png)

**Comment by cassidydotdk** [comment]
Resulting (expected) file structure.

```
 Directory of C:\inetpub\wwwroot\sc901\Data\Unicorn\Example.Project.Website

11/12/2018  17:58    <DIR>          .
11/12/2018  17:58    <DIR>          ..
11/12/2018  18:03    <DIR>          Example.Project.Website.Scaffold
               0 File(s)              0 bytes

 Directory of C:\inetpub\wwwroot\sc901\Data\Unicorn\Example.Project.Website\Example.Project.Website.Scaffold

11/12/2018  18:03    <DIR>          .
11/12/2018  18:03    <DIR>          ..
               0 File(s)              0 bytes

     Total Files Listed:
               0 File(s)              0 bytes
               5 Dir(s)  423,520,804,864 bytes free

C:\inetpub\wwwroot\sc901\Data\Unicorn\Example.Project.Website>
```

**Comment by cassidydotdk** [comment]
Now restoring backup and issuing a new Sync.

Expected result; to have the structure restored, minus the "1", "2" and "3" untracked items.

**Comment by cassidydotdk** [comment]
After issuing "Sync"

```
Example.Project.Website is being synced.
[A] master:/sitecore/content/Example (b5332d60-e7de-4513-8dbc-8e98e562c324)
[A] master:/sitecore/content/Example/Configuration (f573e973-a33c-404c-aec7-3368bb59749d)
[A] master:/sitecore/content/Example/Configuration/Alert Types (cdb04d23-4d9b-4963-8d25-0ba0fec85546)
[A] master:/sitecore/content/Example/Configuration/Event Categories (c146d294-02f5-47f3-b4b9-3d1aa1e03890)
Example.Project.Website sync complete: 8 items evaluated, 4 items modified (4 added, 0 updated, 0 recycled) in 228ms (~28.51ms/item).


[P] Auto-publishing of synced items is beginning.
> Publishing 4 synced items in queue to web
> Published synced items to web (New: 4, Updated: 1, Deleted: 0 Skipped: 1)


Operation completed in 792ms. Want to return to the control panel?

```

**Comment by cassidydotdk** [comment]
Resulting structure: As expected

![image](https://user-images.githubusercontent.com/8483909/49817032-7fac5e00-fd6f-11e8-9870-b1dab038f0fe.png)

**Comment by cassidydotdk** [comment]
If I were to venture a guess; you tested this by deleting the tree - not realising that this would of course also delete the file structure on disk. Then tried a sync of the now non-existent configuration.

**Comment by cassidydotdk** [comment]
Not sure what you're aiming to accomplish. But Unicorn will not try and bring in an empty root folder (and thereby wipe all configuration content).

As for predicate/type etc - all of it is defined in the <defaults> section of Unicorn config. It does not need to be explicitly specified again unless changed.

**Comment by AdamHess** [comment]
looks like i was checking out incorrectly and also needed to restart the app pool. I appreciate the quick response @cassidydotdk  so thank you.
