### ISSUE TITLE
Syncing error when predicate include name contains trailing space

### ISSUE THREAD

**Issue by jrodsmitty** [SitecoreUnicorn/Unicorn#324]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
If I specify a predicate include named with a trailing space, Windows creates the folder without the trailing space, however when Syncing, Unicorn is looking for a folder name including the trailing space.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a MyBug.Unicorn.config file with the following contents
``` xml
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
  <sitecore>
    <unicorn>
      <configurations>
        <configuration name="example">
          <predicate>
            <include name="rich text default " database="core" path="/sitecore/system/Settings/Html Editor Profiles/Rich Text Default" />
          </predicate>
        </configuration>
      </configurations>
    </unicorn>
  </sitecore>
</configuration>
```

2. Run initial serialization to disk
3. Run subsequent Sync
4. When syncing, you get an error that it can't find the files, and asks if you need to perform the initial serialization.

**What is the expected behavior?**
Unicorn would look for the folder name without trailing space.

**Please mention your Sitecore version and Unicorn version.**
Sitecore 9.0.2, Unicorn version 4.0.4

**Comment by cassidydotdk** [comment]
Fixed in: https://github.com/SitecoreUnicorn/Rainbow/commit/cf77c3b868041fc08e49ab3586d515f559f0051c
