### ISSUE TITLE
4.0.6 - Reserialize does not work

### ISSUE THREAD

**Issue by D4rkiii** [SitecoreUnicorn/Unicorn#325]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Can not sync the sitecore items into the file system anymore. Error message appears:

ProjectName.Core is being reserialized.
[D] Clearing existing items from Serialization File System Data Store (if any)
ERROR: The directory name C:\MySerializationFolder\unicorn\ProjectName.Core\SendMailEditor is invalid. (System.ArgumentException)
at System.IO.FileSystemWatcher..ctor(String path, String filter)
at Rainbow.Storage.TreeWatcher..ctor(String rootPath, String filter, Action`2 actionOnChange)
at Rainbow.Storage.SerializationFileSystemTree..ctor(String name, String globalRootItemPath, String databaseName, String physicalRootPath, ISerializationFormatter formatter, Boolean useDataCache)
at Rainbow.Storage.SerializationFileSystemDataStore.CreateTree(TreeRoot root, ISerializationFormatter formatter, Boolean useDataCache)
at Rainbow.Storage.SerializationFileSystemDataStore.InitializeTrees(ISerializationFormatter formatter, Boolean useDataCache)
at Rainbow.Storage.SerializationFileSystemDataStore.Clear()
at Unicorn.SerializationHelper.ReserializeConfigurations(IConfiguration[] configurations, IProgressStatus progress, ILogger additionalLogger)

**If the current behavior is a bug, please provide the steps to reproduce.**
Setup a clean Sitecore 9.0.2 / 9.1 web with unicorn 4.0.6.
Side note: (Sitecore 9.0.2 / 9.1 with unicorn 4.0.4 works perfectly)
Set the targetDataStore outside of your website folder. (Ex: C:\temp)

**What is the expected behavior?**
Pressing the reserialize button should sync the sitecore items defined in the configuration.

**Please mention your Sitecore version and Unicorn version.**
Sitecore 9.0.2 with Unicorn 4.0.6
Sitecore 9.1.0 with Unicorn 4.0.6

**Comment by kamsar** [comment]
Does `C:\inetpub\wwwroot\local.ProjectName.de\App_Data\serialization\ProjectName.Core\SendMailEditor` exist?

**Comment by D4rkiii** [comment]
No it doesnt matter because on the init setup of the unicorn configuration or reserialize.
C:\inetpub\wwwroot\local.ProjectName.de\App_Data\serialization\ProjectName.Core\SendMailEditor is just an example and could be "C:\temp\.

I used the default.config for my further tests and just used the following entries.

<include database="master" path="/sitecore/system/Workflows" />
<include database="master" path="/sitecore/system/Settings" />

And on the init setup the files does not exist because in the first setup you want to sync your sitecore files into your file system.

**Comment by royvou** [comment]
I have the same problem, Sitecore 9.1.0 with latest versions of Unicorn (4.0.6) & Rainbow.(2.0.4)

I think the issue can be found in these 2 commits on Rainbow (and not Unicorn) (since Unicorn 4.0.4 uses Rainbow 2.0.1. instead of 2.0.4)
https://github.com/SitecoreUnicorn/Rainbow/commit/93a976e3a4aa64966ebd979ffe652b518c979d4d#diff-b8c090f01360117ad658242e27d1f4ac
And this whole functionality has been removed in a later commit.
https://github.com/SitecoreUnicorn/Rainbow/commit/3aa2aa9f513fea2fb80c330bea65a05922ff6d38#diff-b8c090f01360117ad658242e27d1f4ac

Looks like the SerializationFileSystemTree can be in a state (not synced e.g. no folder for each include being created yet) where it tries to create a new TreeWatcher (which creates the FileSystemWatcher).

Next step would be to verify if this is the issue. Didn't have time for that yet.

**Comment by cassidydotdk** [comment]
A statement too many was removed, when I took out the .rainbow handling code, which would then prevent the root path from being properly established.

I've pushed a fix to the master branch. This should solve it.

I'm on holidays however, an unable to test it. Please confirm if this fixes the issue.

**Comment by royvou** [comment]
The latest master branch of rainbow does not have this issue.

**Comment by cassidydotdk** [comment]
I'm back from vacation. I will prepare an updated release tomorrow.

**Comment by cassidydotdk** [comment]
Fixed by fd5b0743a5e42fb4a1a8cb35fdd82dafbcbd03e4

**Comment by cassidydotdk** [comment]
https://github.com/SitecoreUnicorn/Rainbow/releases/tag/2.0.5
