### ISSUE TITLE
Unable to access unicorn.aspx on 9.1.0

### ISSUE THREAD

**Issue by markgibbons25** [SitecoreUnicorn/Unicorn#326]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Logging in as admin does not allow going to unicorn.aspx

**If the current behavior is a bug, please provide the steps to reproduce.**
Go to unicorn.aspx, receive 418
Log in as admin
Get redirected to launchpad
Go to unicorn.aspx, receive 418

**What is the expected behavior?**
Go to unicorn.aspx, receive 418
Log in as admin
Get redirected to unicorn.aspx receive 200

**Please mention your Sitecore version and Unicorn version.**
Sitecore 9.1.0
Unicorn 4.0.6

Issue does not exist on Unicorn 4.0.4

**Comment by ampach** [comment]
I've encountered the same issue on Sitecore 9.1.0 and Unicorn 4.0.6

**Comment by coreyasmith** [comment]
Sitecore 9.1 doesn't correctly load the context user from the identity server for paths that don't resolve to a site, such as `/unicorn.aspx`. As a quick fix, you can add the following patch to your Sitecore instance:

```xml
<configuration>
  <sitecore>
    <pipelines>
      <owin.cookieAuthentication.validateIdentity>
        <processor type="Sitecore.Owin.Authentication.Pipelines.CookieAuthentication.ValidateIdentity.ValidateSiteNeutralPaths, Sitecore.Owin.Authentication">
          <siteNeutralPaths hint="list">
            <path hint="unicorn">/unicorn.aspx</path>
          </siteNeutralPaths>
        </processor>
      </owin.cookieAuthentication.validateIdentity>
    </pipelines>
  </sitecore>
</configuration>
```

This won't fix the issue where you get sent to the Launch Pad after logging in from `/unicorn.aspx`, but the Unicorn control panel will now work after logging in. The redirect will require a new version of Unicorn.

**Comment by cassidydotdk** [comment]
Fixed in https://github.com/SitecoreUnicorn/Unicorn/releases/tag/4.0.7

**Comment by deeja** [comment]
in `/src/Foundation/Serialization/code/Helixbase.Foundation.Serialization.csproj`
```
  <None Include="App_Config\Include\Unicorn\Unicorn.UI.IdentityServer.config">
       <SubType>Designer</SubType>
    </None>
```
Needs to change to
```
 <Content Include="App_Config\Include\Unicorn\Unicorn.UI.IdentityServer.config">
     <SubType>Designer</SubType>
  </Content>
```

**Comment by cassidydotdk** [comment]
`/src/Foundation/Serialization/code/Helixbase.Foundation.Serialization.csproj` has nothing to do with this project.

**Comment by deeja** [comment]
Aw damn it, posted this in the wrong window

**Comment by tillito77** [comment]
After hours of looking and trying, I found:
The URL for Unicorn after this patch is **case sensitive**! The patch does not work when I enter
https://cm.mum.localhost/Unicorn.aspx?sc_lang=en
but it works - that means it recognizes me as an administrator - when I change it to
https://cm.mum.localhost/unicorn.aspx?sc_lang=en

**Comment by cassidydotdk** [comment]
> After hours of looking and trying, I found:
> The URL for Unicorn after this patch is **case sensitive**! The patch does not work when I enter
> https://cm.mum.localhost/Unicorn.aspx?sc_lang=en
> but it works - that means it recognizes me as an administrator - when I change it to
> https://cm.mum.localhost/unicorn.aspx?sc_lang=en

It is defined here: https://github.com/SitecoreUnicorn/Unicorn/blob/8716fe4ddb0d14165d222cebaae56dad41992805/src/Unicorn/Standard%20Config%20Files/Unicorn.UI.config#L56

And is picked up here:
https://github.com/SitecoreUnicorn/Unicorn/blob/8716fe4ddb0d14165d222cebaae56dad41992805/src/Unicorn/ControlPanel/UnicornControlPanelPipelineProcessor.cs#L40

To my knowledge it should not be case-sensitive unless you're on a very old version.  `StringComparison.OrdinalIgnoreCase`.

**Comment by coreyasmith** [comment]
`Unicorn.aspx` doesn't work because the `Sitecore.Owin.Authentication.Pipelines.CookieAuthentication.ValidateIdentity.ValidateSiteNeutralPaths` processor case-sensitively compares the URL path to the `siteNeutralPath` elements:

```csharp
this.SiteNeutralPaths.Any<string>(new Func<string, bool>(args.Context.Request.Uri.PathAndQuery.StartsWith)
```

As @cassidydotdk pointed out, only `unicorn.aspx` is patched in here, not other case variants: https://github.com/SitecoreUnicorn/Unicorn/blob/8716fe4ddb0d14165d222cebaae56dad41992805/src/Unicorn/Standard%20Config%20Files/Unicorn.UI.IdentityServer.config.disabled#L20

@tillito77 you have a few options:
1. Open a bug with Sitecore to put pressure on them to fix this in future versions (do this anyway, please).
2. Embrace lowercase URLs. 🙂
3. Patch additional cases you'd like to support in your own custom config file.
4. Create a custom `ValidateSiteNeutralPaths` implementation that properly does a case-insensitive compare.

**Comment by tillito77** [comment]
I chose option 2.
Basically, I wanted to provide a neat help for others tapping in this problem.

**Comment by cassidydotdk** [comment]
I mean it would be a small issue to patch in 

```
<path hint="unicorn">/unicorn.aspx</path>
<path hint="j00nicorn">/Unicorn.aspx</path>
```

but then would I also need

```
<path hint="uni-corn">/unicorn.Aspx</path>
<path hint="uni--corn">/Unicorn.Aspx</path>
```

? 😎

I don't know... I feel Sitecore is in the wrong here, but maybe assuming case-sensitivity is natural under the circumstances. I don't know. 

Alternatively - I could add code in the processor Unicorn owns, and blow up if the URL is not all lower-case. Then Unicorn could at least detect this and warn the users. But what then if Sitecore later fixes it?

IDK. I might take a look if there is anything simple I could do to approach it. Open to suggestions.
