### ISSUE TITLE
Critical Message when creating new item versions

### ISSUE THREAD

**Issue by erik-schafer** [SitecoreUnicorn/Unicorn#332]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a user creates a new version of a serialized item, and attempts to save it, they get a "Critical Message From Unicorn", that most of the fields do not match serialization, and that continuing "MAY CAUSE LOST WORK".  

When a user creates a new version of a serialized item only the Created By/ Created Date fields are saved into serialization, with no mention of other fields.

**If the current behavior is a bug, please provide the steps to reproduce.**
Navigate to an item that is serialized by Unicorn.  Save it (verify no conflict, could also do a snyc/serialzie).  Create a new version, optionally modify field values.  Attempt to Save, observe the warning dialog.

**What is the expected behavior?**
Unicorn should properly serialize the first save of an item version without a warning.

**Please mention your Sitecore version and Unicorn version.**
Sitecore.NET 8.2 (rev. 161221)
Unicorn Version 4.0.0

**Comment by AvanDriel** [comment]
Encountering the same error as well. When creating, for example, a second version, the fields that were edited in version one are not synced for the second version. 
Weird thing is, when creating a third version, all of a sudden the fields edited in the first version, are updated in version 2's yml. The third version once again has no serialization of edited fields in one of the earlier versions.

This issue is quite severe, as it prevents editors from doing anything

**Comment by cassidydotdk** [comment]
Can anyone confirm this behaviour on 4.0.7 with a Rainbow 2.0.5 or later?

**Comment by AvanDriel** [comment]
I've discussed this on the sitecore stackexchange, and we have decided to turn off live content sync for content. The thread could be found [here](https://sitecore.stackexchange.com/questions/16512/unable-to-sync-page-versions-with-unicorn) , maybe it helps for @erik-schafer to determine to do the same.

Note: you can still manually sync content if you want, by going to the unicorn control panel and serializing from there. That way you could still sync content in-between environments. (the manual sync does correctly sync the different versions)

**Comment by cassidydotdk** [comment]
Thanks for the clarification @AvanDriel - the thread does indeed explain the issue in detail.

I will put it on the backlog to see if there's anything that can be changed in our end; but there are other things needing more immediate focus going on right now.

For the time being, the scenario here isn't really a supported usage.

> Don't use Unicorn to serialize actively versioned or workflow-enabled content (e.g. non-developer items). You can easily have two people create totally different "version 2" (or even v3, overwriting someone else's v2) content on different locations, and merging those is probably not what you want. It may be relatively safe during initial development if sharing test content, but be wary.
