### ISSUE TITLE
Unversioned fields persists in the YML file when version is removed

### ISSUE THREAD

**Issue by zaheer-tariq** [SitecoreUnicorn/Unicorn#335]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I remove a language version the unversioned fields persists in the YML file.

**If the current behavior is a bug, please provide the steps to reproduce.**
Both item and template locations are controlled by Unicorn.
1. Create a new template with Unversioned field in a Sitecore solution that has multiple languages.
1. Create an item based on Step 1.
1. Add item version in all languages
1. Now remove one language version e.g. fo. You will see that the version is removed form yml file but the Unversioned field still exists.

Example yml after removing version

- Language: fo
  Fields:
  - ID: "76eeb204-5070-4e97-b64f-1bf7f5f94ca4"
    Hint: UnversionedFields
    Value: "UnversionedFields  [FO]"
  Versions:
- Language: "fo-FO"

**What is the expected behavior?**
The yml file should not have Unversioned field as well.

**Please mention your Sitecore version and Unicorn version.**
Sitecore = 9.0.2
Unicorn = 4.0.7

**Comment by kamsar** [comment]
This is how unversioned fields work. They are not tied to a version - they are tied to a language.

There is no way to "delete the language" through the Sitecore UI, only all the versions in said language. Thus, the unversioned field values persist even if no versions in that language are present.
