### ISSUE TITLE
No Login Required On Fresh NuGet Install

### ISSUE THREAD

**Issue by ONeillJ** [SitecoreUnicorn/Unicorn#336]
**Do you want to request a *feature* or report a *bug*?**
Potential bug. It is possible one of our configs are affecting Unicorn somehow.

**What is the current behavior?**
Unicorn.aspx page is accessible to everyone on a default install/config.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Add Unicorn 4.0.7 nuget package to Sitecore 8.2 Update 4 project
- Build project
- View mysite/unicorn.aspx

**What is the expected behavior?**
I would expect a message saying "You need to login as Admin to access this page" or something along those lines.

**Please mention your Sitecore version and Unicorn version.**
Sitecore 8.2 Update 4
Unicorn 4.0.7

I searched around for an answer to this and couldn't find anything. I also went through all of the configs and didn't see anything that clearly mentions turning on/off Authentication/Authorization.

If there is anything else I can provide to help enable this feature let me know please.

**Comment by kamsar** [comment]
Turn debug compilation off
________________________________

**Comment by ONeillJ** [comment]
Wow, thank you so much! I am so glad it was that simple. Is this mentioned somewhere in the documentation that I missed?

**Comment by kamsar** [comment]
Pretty sure it is. The convention has been there for a very long time :)
________________________________

**Comment by ONeillJ** [comment]
This is solved so I will close it. User Error strikes again. :)
Thanks again.
