### ISSUE TITLE
Not bucketable item in bucket won't be deserialized correctly

### ISSUE THREAD

**Issue by wene37** [SitecoreUnicorn/Unicorn#341]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If I have a bucket and inside this an item that is not bucketable, then the serialization is working fine. But on deserialization the item is moved to bucket structure like it would be bucketable.

I believe the problem is, that the item is created first as "normal" item and so Sitecore is going to move it into the bucket structure. Afterwards the fields of the item get updated by Unicorn and the item is marked as not bucketable like it's defined in the serialized file.

Maybe this has something to do with issue #283. There was a similar problem.

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
The item should be created and updated with all correct values in one single action.

**Please mention your Sitecore version and Unicorn version.**
Sitecore: Sitecore.NET 9.1.0 (rev. 001564)
Unicorn: 4.0.8

**Comment by wene37** [comment]
FYI: I could fix this with a workaround by overriding IsTemplateBucketable in PipelineBasedBucketProvider. I just replaced with following code:

```
public override bool IsTemplateBucketable(ID templateId, Database database)
{
  if (HttpContext.Current != null && 
      HttpContext.Current.Request.Url.PathAndQuery.StartsWith("/unicorn.aspx"))
  {
    return false;
  }

  return base.IsTemplateBucketable(templateId, database);
}
```

**Comment by cassidydotdk** [comment]
As such, every item is created as "normal" until filled with field values. I must be honest and say, I find the whole idea of having non bucketable items inside a bucket for questionable - at best.

But all that aside, if you open your developer tab in Sitecore, use Sitecore to serialize the entire structure, delete all child items in your bucket and then recreate the tree from what was serialized, what happens?

**Comment by wene37** [comment]
It happens the same. So Unicorn has the same behaviour as Sitecore. Nevertheless I still think that this should not happen. I think that Unicorn should disable (or at lease have an option to disable) all handlers while deserialize items. This because all handlers have been run while creating the item and do not need to run again when deserializing.

As Sitecore created the property "Bucketable", I believe it's absolutely correct to have items in a bucket, that are not bucketable. Otherwise this property would be for nothing.

**Comment by cassidydotdk** [comment]
Look, I hear you. But then there's the official documentation.

https://doc.sitecore.com/users/91/sitecore-experience-platform/en/item-buckets.html

> Important
You should not store both regular and bucketable items in an item bucket. This can introduce unnecessary complexities.

Which is exactly what this is. An unnecessary complexity.

Unicorn already provides you tools to hook whatever custom code you want into the process; you have the sync begin and sync end pipelines.

When Sitecore's native deserializer cannot deal with this, I have no place to look for official guidance on how to implement this functionality in any official or semi official capacity. Personally - while a curiosity - I also feel this to be too much of an edge case to invest development effort into.

You're welcome to submit a PR against the `develop` branch for review if you feel up for the challenge yourself.
