### ISSUE TITLE
SerializationFinishedEvent causes all caches to be cleared in Content Delivery when synchronization finishes in Content Management

### ISSUE THREAD

**Issue by alexsab1** [SitecoreUnicorn/Unicorn#343]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

[SendSerializationCompleteEvent.cs](https://github.com/SitecoreUnicorn/Unicorn/blob/master/src/Unicorn/Pipelines/UnicornSyncEnd/SendSerializationCompleteEvent.cs) raises remote SerializationFinishedEvent which causes all caches to be cleared in Content Delivery when synchronization finishes in Content Management. This causes major production performance issue with Azure SQL DTU peaking at 100% for a very long time.

DEBUG Log Entry in Content Management:

> ManagedPoolThread #0 15:18:47 WARN  All caches have been cleared. This can decrease performance considerably. DEBUG entries have to be enabled in log4net to see the corresponding stack trace.
> ManagedPoolThread #0 15:18:47 DEBUG All caches have been cleared. Stack trace:
>    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
>    at System.Environment.get_StackTrace()
>    at Sitecore.Caching.DefaultCacheManager.ClearAllCaches()
>    at Sitecore.Data.Serialization.DefaultSerializationManager.<Initialize>b__25_0(SerializationFinishedEvent event)
>    at Sitecore.Eventing.Subscription`1.Invoke(Object instance, EventContext context)
>    at Sitecore.Eventing.EventProvider.RaiseEvent(Object event, Type eventType, EventContext context)
>    at Unicorn.Pipelines.UnicornSyncEnd.SendSerializationCompleteEvent.RaiseEvent(String databaseName)
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)
>    at Sitecore.Jobs.JobRunner.RunMethod(JobArgs args)
>    at (Object , Object )
>    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
>    at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
>    at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
>    at Sitecore.Jobs.Job.DoExecute()
>    at Sitecore.Jobs.Job.ThreadEntry(Object state)
>    at Sitecore.Threading.ManagedThreadPool.ProcessQueuedItems()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

DEBUG Entry in Content Delivery:

> ManagedPoolThread #0 15:18:48 WARN  All caches have been cleared. This can decrease performance considerably. DEBUG entries have to be enabled in log4net to see the corresponding stack trace.
> ManagedPoolThread #0 15:18:48 DEBUG All caches have been cleared. Stack trace:
>    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
>    at System.Environment.get_StackTrace()
>    at Sitecore.Caching.DefaultCacheManager.ClearAllCaches()
>    at Sitecore.Data.Serialization.DefaultSerializationManager.<Initialize>b__25_0(SerializationFinishedEvent event)
>    at Sitecore.Eventing.Subscription`1.Invoke(Object instance, EventContext context)
>    at Sitecore.Eventing.EventProvider.RaiseEvent(Object event, Type eventType, EventContext context)
>    at Sitecore.Eventing.EventQueue.ProcessEvents(Action`2 handler)
>    at Sitecore.Eventing.EventProvider.RaiseQueuedEvents()
>    at Sitecore.Data.Eventing.EventQueueMonitor.AlarmClock_Ring(Object sender, EventArgs e)
>    at Sitecore.Services.AlarmClock.<>c__DisplayClass11_0.<Heartbeat_Beat>b__0(Object state)
>    at Sitecore.Threading.ManagedThreadPool.ProcessQueuedItems()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Two instances are required: Content Management and Content Delivery with event queue enabled.
2. Enable Cache clearing debugging: https://kb.sitecore.net/articles/973943.
3. Sync in manually or using powershell (https://sitecore.stackexchange.com/a/5588).
4. Open Content Management log file and look for log entry with text "WARN  All caches have been cleared. This can decrease performance considerably. DEBUG entries have to be enabled in log4net to see the corresponding stack trace."
5. Open Content Delivery log file and look for log entry with text "WARN  All caches have been cleared. This can decrease performance considerably. DEBUG entries have to be enabled in log4net to see the corresponding stack trace."

**What is the expected behavior?**

Expected behavior is NOT to clear all cache in Content Delivery,

**Please mention your Sitecore version and Unicorn version.**

Sitecore 9.0.2

Unicorn 4.0.4

**Comment by alexsab1** [comment]
In Unicorn.config I see the following:

> 
> 			
> 			<unicornSyncEnd>
> 				<processor type="Unicorn.Pipelines.UnicornSyncEnd.SendSerializationCompleteEvent, Unicorn" />
> 			</unicornSyncEnd>

Can this configuration be commented safely?

**Comment by cassidydotdk** [comment]
We're just following Sitecore's own implementation pattern here. Below, find the code from Sitecore.Kernel for Serialization Complete:

```
    private void DeserializationFinished(string databaseName)
    {
      EventManager.RaiseEvent<SerializationFinishedEvent>(new SerializationFinishedEvent());
      this.factory.GetDatabase(databaseName, false)?.RemoteEvents.Queue.QueueEvent<SerializationFinishedEvent>(new SerializationFinishedEvent());
    }
```

It raises the event both locally and sends it to remotes.

You _can_ disable this file but you could potentially set yourself up to fail pretty badly. Say if you were synchronising "core" items that a CD server was reading. If you know this to not be the case, go ahead and disable firing the event.

I'll look into perhaps adding a few more granular configuration options to this pipeline. For now, if you need a different behaviour, either comment this handler out or write your own based on ours.

**Comment by alexsab1** [comment]
@cassidydotdk Thank you for the detailed answer! The fact that this is Sitecore's functionality is going to change our solution a bit. 

We reviewed our core files and found that all of them are CM related. So we will implement our own handler based on existing SendSerializationCompleteEvent.cs class to remove Remote events.

Also, I found in Sitecore's document that starting from 9.1 core database is no longer referenced in CD:

> The Core database is not referenced by the Content Delivery role in Sitecore 9.1 and later.

https://doc.sitecore.com/developers/91/platform-administration-and-architecture/en/content-delivery--cd-.html

**Comment by cassidydotdk** [comment]
Yep. To be honest, it _is_ something we have been discussing to do differently. That said, we try to mimic what Sitecore does internally as much as possible when in doubt, since there really isn't much (any) documentation available on how to "officially" implement something like Unicorn ;-)

Perhaps we might move to :delete the processor in a 9.1 specific configuration file. If not for reasons of `core`, I can't really think of a case where it makes sense to broadcast a "dump all caches" to all front end servers just because the CM has deserialized something. They will be informed when said changes are published, which _ought_ to be good enough imo.

**Comment by cassidydotdk** [comment]
Will gladly review and accept a PR that adds a `broadcast` parameter to that processor however ;-) :D

**Comment by alexsab1** [comment]
@cassidydotdk I have not yet contributed to this repo, are there any rules for PRs or naming conventions? 

Thanks

**Comment by cassidydotdk** [comment]
Probably, but in documented form.... less so ;-)

PR against the `develop` branch and common sense. Those two will go a long way. For this specific task, knowledge about `Sitecore.Configuration.Factory` goes a long way too, since it will do 90% of the job required.
