### ISSUE TITLE
Non-fatal warnings break role sync in 4.0.3

### ISSUE THREAD

**Issue by lkozak** [SitecoreUnicorn/Unicorn#346]
Bug in Version 4.0.3: If a non-fatal warning occurs during the first phase of deserialisation Unicorn will quit processing the configuration and the roles will never get synced. Instead Unicron will proceed with the next configuration.

Feature.Breadcrumb is being synced. 
Feature.Breadcrumb sync complete: 12 items evaluated, 0 items modified (0 added, 0 updated, 0 
Feature.Breadcrumb roles are being synced.  <<--- THIS WON'T HAPPEN
Feature.Breadcrumb role sync complete. 

Is there a way to 'promote' non-fatal warnings to normal errors so that our CI simply breaks?

**Comment by kamsar** [comment]
Install the latest version, pretty sure this is fixed already
________________________________
