### ISSUE TITLE
"One or more items have been changed. ...Overwrite?" on page saves in EE

### ISSUE THREAD

**Issue by sitecorepm** [SitecoreUnicorn/Unicorn#351]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Getting the popup "One or more items have been changed. Do you want to overwrite these changes?" constantly when saving page items.
As detailed here: https://community.sitecore.net/general/f/16/t/2285

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a page item with components on it.
1. Add multiple versions to the components such that they do not match the page item's version.
1. Open page in EE, make a change to the page where data on a component item is changed.
(I'm sort of guessing on these "reproduce" steps.. if this doesn't work I'll go through the effort to install a clean instance and figure it out for real.)

**What is the expected behavior?**
It should save with no popup message about overwriting changes.

**Please mention your Sitecore version and Unicorn version.**
SC 9.1
Unicorn 4.0.7

NOTES:
I tracked it down to this override: Unicorn.ExperienceEditor.Speak.Ribbon.Requests.SaveItem.TransparentSyncAwareCheckRevision

It seems like the overridden code changed at some point to fix the above mentioned bug but Unicorn's override doesn't integrate the fix.

Specifically this line,
```
// Unicorn override
Item item = base.RequestContext.Item.Database.GetItem(saveItem.ID, Language.Parse(base.RequestContext.Language), Sitecore.Data.Version.Parse(base.RequestContext.Version));
```
vs.
```
// SC 9.1 code base
Item item = base.RequestContext.Item.Database.GetItem(saveItem.ID, saveItem.Language, saveItem.Version);
```

**Comment by cassidydotdk** [comment]
I've pushed this out in https://github.com/SitecoreUnicorn/Unicorn/releases/tag/4.1.1-pre2 - if I could get you to confirm that this fixes the issue on your instance, that would be great :-)

(which is another way of saying, I'm hoping to not have to set up and configure an entire 9.0 and 9.1 instance to reproduce this issue and test it)

**Comment by sitecorepm** [comment]
Sorry, I just saw this. I'll try it today.

**Comment by sitecorepm** [comment]
I'm getting this error after updating from 4.0.7 to 4.1.1-pre2... Any
suggestions?

*Method 'Save' in type 'Unicorn.Data.ConfigurationDataStore' from assembly
'Unicorn, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null' does not
have an implementation*

[image: image.png]

**Comment by cassidydotdk** [comment]
Yea, I think you probably have some leftover assemblies in your obj folder. Run a full "Clean Solution" and republish the solution. Also make sure you're using the 4.1.0+ version of Unicorn.config.

**Comment by cassidydotdk** [comment]
Also; the 4.1.0 release needs Rainbow 2.1.0

**Comment by sitecorepm** [comment]
Ah yes. That was it. Nuget was set to ignore dependencies and I missed updating Rainbow. It's working now.

And yes, I can confirm that this patch fixes the reported issue on SC 9.1

**Comment by cassidydotdk** [comment]
Perfect, thank you for confirming :-)    I expect 4.1.1-pre2 to be promoted to a full release (4.1.1) sometime this weekend :-)

**Comment by sitecorepm** [comment]
Excellent! Thanks for the quick turnaround!
