### ISSUE TITLE
Unicorn files are not getting serialized in accordance to the content tree structure, if the number of sub-items are more

### ISSUE THREAD

**Issue by sivagopi123** [SitecoreUnicorn/Unicorn#360]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
When we re-serialize the content from Sitecore to the local folder, the sub-items are getting created as separate folder with a folder created with the guid of the parent item, without respecting the parent child relationship of that item and its content tree.
**If the current behavior is a bug, please provide the steps to reproduce.**
Step 1: Add multiple content with multiple sub items. Have alteast 5 to 7 level of sub-item. Create multiple child elements (more than 7 to 8 items) to the last descendant item in the content hirarchy. 
Step 2: Now when we re-serialize the content, instead of re-serializing the yml files by respecting the parent child relationship of the content tree, Unicorn creates some of the items automatically ouside the content heirarchy by creating a new folder with the name equal to the guid of the parent item of those items. 
**What is the expected behavior?**
No matter how many sub-items we create in the content tree, all the  yml files must be placed inside the corresponding parent item and should respect the parent child relationship of the content tree
**Please mention your Sitecore version and Unicorn version.**
Sitecore 9.2
Unicorn 4.1.1

**Comment by kamsar** [comment]
This is expected behavior, and has to do with respecting Windows' 240-char
max path lengths. If your item path gets too long, it has to "loop it back"
and restart the subtree under a new location.

**Comment by sivagopi123** [comment]
Is there anywhere we can modify this 240 char max path length configuration.

**Comment by cassidydotdk** [comment]
Not currently. But understand; the problem lies in your file system and your tooling. Changing the configuration does nothing, if your OS file system doesn't support it.
