### ISSUE TITLE
Branch Id not syncronizing

### ISSUE THREAD

**Issue by eloycm** [SitecoreUnicorn/Unicorn#364]
when I synchronize items on a developer installation of sitecore, the branchid field is not synchronized, even when the branch from where the items were created already exist in the instance. branchid is always unknown. The ymls contain a branchid value but the value is never passed to the sitecore instance. To aggravate things unicorn sync always sees the object as different (the yml with branchid the sitecore without branchid) and all the branched items are updated again and again on every synchronization. the branchid field doesn't ever get populated.

**Comment by cassidydotdk** [comment]
This is by design. There is a config setting to enable the syncing of Branch Id again, but use it at your own risk. To my knowledge the underlying bug in the Sitecore API has not been addressed at this time.

See: https://github.com/SitecoreUnicorn/Unicorn/issues/283

**Comment by cassidydotdk** [comment]
And for the record; if items are being synced over and over again - it is not due to Branch Id. There's something else in play. You're looking in the wrong place.
