### ISSUE TITLE
Invalid CRLF characters

### ISSUE THREAD

**Issue by AlexxCj** [SitecoreUnicorn/Unicorn#367]
Hi all,

I'm trying to install Unicorn 4.1.1 and when I'm trying to run the script sample.ps1 I get this error: "Sync-Unicorn : Specified value has invalid CRLF characters. Parameter name: value".  It indicate line no 10 of the script which contain "Sync all" configurations.

Sitecore version: 8.2

Thanks!

**Comment by cassidydotdk** [comment]
Not enough info here for me to work with.
