### ISSUE TITLE
SendSerializationCompleteEvent not raised properly in Sitecore 9.2

### ISSUE THREAD

**Issue by tomunderhill** [SitecoreUnicorn/Unicorn#370]
Bug in Sitecore 9.2, Unicorn 4.1.1

I've noticed an error in our logs on sync, "Cannot find property with 'QueueEvent' method. SerializationFinishedEvent is not rised."

I tracked it down to the SendSerializationCompleteEvent - looks like some code has been added in the latest Unicorn version to find the RaiseEvent method by reflection. Anyway, it is not working on 9.2.0.

I have reverted to just using `remoteEvents.EventQueue.QueueEvent(new SerializationFinishedEvent())` instead of the reflection (I tried to fix it but it was getting a bit complex as there are now two methods for QueueEvent).

**Comment by cassidydotdk** [comment]
Does this happen to you locally as well?   I'm running a 4.1.1 on a 9.2, and see no such problem.

**Comment by tomunderhill** [comment]
Yes, locally and on a couple of environments. 

The offending line is:

`var eventQueue = remoteEventsType.GetProperties().FirstOrDefault(property => property.GetType().GetMethod("QueueEvent") != null);`

First off, I can't see how this could work as in my case property.GetType() returns a reflection type. I would have thought this should be property.PropertyType. But if I make it so:

`var eventQueue = remoteEventsType.GetProperties().FirstOrDefault(property => property.PropertyType.GetMethod("QueueEvent") != null);`

Then I get an ambiguous match because there are two QueueEvent methods with different signatures.

**Comment by cassidydotdk** [comment]
This should be fixed in #378 

It's released to NuGet as 4.1.2-pre1. https://github.com/SitecoreUnicorn/Unicorn/releases/tag/4.1.2-pre1

**Comment by mitikov** [comment]
Reproducible for 9.3

**Comment by dreschner** [comment]
Just for information: We see the same error message with unicorn 4.1.1 and sitecore 8.2.7. We'll try the 4.1.2-pre1 version and report here if it helps.
