### ISSUE TITLE
FieldFilter is not respected for Deserialization process

### ISSUE THREAD

**Issue by ravikumarmvs1** [SitecoreUnicorn/Unicorn#372]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Unable to exclude __Security field for Deserialization.
**If the current behavior is a bug, please provide the steps to reproduce.**
Include below configuration in <defaults> section:
`<fieldFilter type="Rainbow.Filtering.ConfigurationFieldFilter, Rainbow" singleInstance="true">
        <exclude fieldID="{DEC8D2D5-E3CF-48B6-A653-8E69E2716641}" note="'__Security' field on Standard Template" />
    </fieldFilter>`
**What is the expected behavior?**
It should probably exclude __Security field from Unicorn sync.
But unfortunately FieldFilter setting is not respected for Deserialization (updating item) process.
Please let me know if there is any existing solution to achieve this requirement. 
**Please mention your Sitecore version and Unicorn version.**
Sitecore 9.1, Unicorn 4.0.4

**Comment by cassidydotdk** [comment]
Please use the issue template. Also include relevant configuration snippets.

**Comment by ravikumarmvs1** [comment]
> Please use the issue template. Also include relevant configuration snippets.

I have just updated the issue.

**Comment by ravikumarmvs1** [comment]
Looks like after upgrading to Unicorn 4.1.0, we have an option of using fieldtransformations.
