### ISSUE TITLE
How do I remove or disable Unicorn on an existing Sitecore project/site?

### ISSUE THREAD

**Issue by michaelmmcrae1** [SitecoreUnicorn/Unicorn#373]
Sitecore version 8.1, not positive on the Unicorn version.

I would like to disable or remove the Unicorn syncing from my project (inherited a project, need to make some quick changes, Unicorn won't let us create any new Sitecore items unless we sync, but we are not at all familiar with Unicorn, so we'd rather just get rid of it for now).

How do I do so?

I disabled Unicorn.config -> Unicorn.config.disabled

But that just leads to an error on load of every page:

Could not find configuration node: /sitecore/unicorn/configurationProvider

**Comment by PaulsonMac** [comment]
Hi team, do we have an option in Unicorn for the above?

**Comment by markgibbons25** [comment]
Delete or disable all Unicorn and Rainbow configs, and delete or disable all your custom serialization configs.

**Comment by PaulsonMac** [comment]
I tried this already... But this didn't work.

**Comment by cassidydotdk** [comment]
Must be magic then. It's a Unicorn, after all ;-)

**Comment by PaulsonMac** [comment]
I tried it in the Habitat solution.. When I navigated to /unicorn.aspx, I
got some predicate-related errors. Would be great to have something like
kind of setting false to a parameter in a config..

**Comment by PaulsonMac** [comment]
Have a question guys : Just want to know if there is a way to temporarily disable unicorn.. Can anyone provide some details on this?

**Comment by PaulsonMac** [comment]
https://github.com/Sitecore/Sitecore.HabitatHome.Platform#disable-unicorn-serialization

**Comment by cassidydotdk** [comment]
Look. The short story is; Unicorn gets patched in to Sitecore via its config files. If those are removed, Unicorn doesn't exist, as far as Sitecore is concerned. If you remove the configs yet receive Unicorn related errors, you did not remove the configs.

The longer story is; Unicorn blocks you from making changes like this for a reason. Just disabling will only make the problem seem to disappear; the root problem of a solution not in sync with its repository remains.

**Comment by LM-ARKAV** [comment]
Hello Guys,

I'm using Unicorn 4, and getting the below issue where my children items are placed with GUID as a folder name along with the Root folder. Do we have any fix for this?
![image](https://user-images.githubusercontent.com/57650497/86884403-1694f400-c126-11ea-8c5b-f0960b0473f7.png)
