### ISSUE TITLE
Auto publish fails for buckets when syncing a full content tree

### ISSUE THREAD

**Issue by nickwesselman** [SitecoreUnicorn/Unicorn#374]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When syncing a full content tree that contains a bucket, the bucket and its contents fail to publish.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Ensure Auto Publish config is enabled.
1. Create a tree of serialized items for a full site, which includes a bucket with some items in it.
1. Delete that tree in the Content Editor, and publish to ensure it is deleted from web as well.
1. Sync the tree of items. Unicorn should attempt to auto-publish.
1. View the content in the `web` database -- the bucket is not published.

Best I can tell of what's happening:

1. `Unicorn.Publishing.ManualPublishQueueHandler` adds the synced items to the publish queue.
1. `Sitecore.Buckets.Pipelines.Publish.AddBucketFoldersToQueue` finds all the bucketed items, and adds their parents to the queue in a separate enumerable, always 2nd in the list.
1. The bucket folders list is processed first during publishing, but these items fail to publish because the site root and home item do not exist yet.
1. The Unicorn manual queue is published, but the bucket folders are skipped by `Sitecore.Publishing.Pipelines.Publish.ProcessQueue` because it sees they have already been processed in the same publishing operation.

This does not affect a smart publish of the site root from the Content Editor, because as a subitem/deep publish, the bucketed items don't appear explicitly in the publish queue, so `AddBucketFoldersToQueue` doesn't add them.

**What is the expected behavior?**
All sync'd items are published, including bucketed items.

**Workaround/Potential Solution**

Patch the `ManualPublishQueueHandler` after `AddBucketFoldersToQueue`. This works for me but not sure if it would create problems in other serialization scenarios.

```
      <pipelines role:require="Standalone or ContentManagement">
        <publish>
          <!--
            Move the Unicorn publish queue after AddBucketFoldersToQueue to avoid issues with bucket publishing.
          -->
          <processor type="Unicorn.Publishing.ManualPublishQueueHandler, Unicorn">
            <patch:delete />
          </processor>
          <processor patch:after="*[@type='Sitecore.Buckets.Pipelines.Publish.AddBucketFoldersToQueue, Sitecore.Buckets']" type="Unicorn.Publishing.ManualPublishQueueHandler, Unicorn"/>
        </publish>
      </pipelines>
```

**Please mention your Sitecore version and Unicorn version.**
Reproduced on 9.2 and 9.3 with Unicorn 4.1.1.

**Comment by cassidydotdk** [comment]
Fixed in https://github.com/SitecoreUnicorn/Unicorn/releases/tag/4.1.2-pre9.

Thanks for the report :-)
