### ISSUE TITLE
Updating original items through Unicorn does not give change warning for cloned items 

### ISSUE THREAD

**Issue by matthew0102** [SitecoreUnicorn/Unicorn#379]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Updating original items through Unicorn does not give change warning for cloned items 

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create an item in Sitecore
2. Create a clone of the item in Sitecore
3. Serialize the original item in Unicorn
4. Update any field value of the cloned Item
5. Change the original item file outside your instance (ex. manually update yml file field value in notepad)
6. Sync the original item (this would change the value of the item)
7. Check the cloned item, it does not trigger a warning that the original item has changed (This causes the content editor to NOT be able to accept or reject the change that happened to the original item, it automatically rejects)

**What is the expected behavior?**
The cloned item should have triggered a warning notification that the original item has changed.
![image](https://user-images.githubusercontent.com/50011220/76054556-0a4c2f00-5fac-11ea-97d7-7522e1257be3.png)

**Please mention your Sitecore version and Unicorn version.**
Sitecore 9 Update 2
Unicorn v4.0

**Comment by kamsar** [comment]
Unicorn does not update the search indexes or links database for synced items by default because it is comparatively very slow. I bet your clones are probably using the link database for their tracking, so enabling indexing and link updates for synced items is probably what you are looking for:

https://github.com/SitecoreUnicorn/Unicorn/blob/0b8cabf0e36c101018487e162eccb1a64a988657/src/Unicorn/Standard%20Config%20Files/Unicorn.Configs.Default.example#L121

It is much slower so generally you only want to enable this for scenarios where it is required (generally only for content, not for templates and such).

**Comment by matthew0102** [comment]
I've tried adding the syncConfiguration to my serialization for the original item, but unfortunately it still does not work. I did see that the links and search index were updated on the unicorn logs together with the updated field, but there was still no notification on the cloned items that the original item has changed

**Comment by cassidydotdk** [comment]
You need to leave the setting enabled, disable transparent sync (as this is something you changed for no reason) and then issue a full rebuild of the LinkDatabase via Sitecore control panel.

**Comment by matthew0102** [comment]
@cassidydotdk I set the updateLinkDatabase to enabled. I did NOT enable transparent sync, it's not there in the repro steps.
I did the repro steps again then did a full rebuild of the LinkDatabase (core, master, and web), but the issue still persists. The notifications on the clones does not show up when a change in the original item was caused by a Unicorn Sync.
Please make this issue still Open

**Comment by cassidydotdk** [comment]
Try it on the latest pre-release. 4.1.2-pre2.

**Comment by matthew0102** [comment]
Thank you for the suggestion. I tried it on the latest release, I upgraded to the latest version 4.1.2-pre2 but the notifications still didn't show.
To my knowledge, the notifications shows up when there is a change in the original item. This change will call a pipeline that would create the notification and store that in the SQL database.
It seems that Unicorn is not calling/triggering the pipeline when it updates the item when syncing.
I believe the pipeline is Sitecore.Pipelines.GetContentEditorWarnings.Notifications

**Comment by cassidydotdk** [comment]
What happens if you use the built-in serializer?   i.e. 

- Disable Unicorn
- "Serialize Tree" on the same content you have under Unicorn control
- Make some changes on disk, for some of the serialized content
- "Revert Tree" back

Does the Cloned items show these updates?

**Comment by matthew0102** [comment]
I have tried what you suggested and found out that the notifications does not show up as well.

**Comment by cassidydotdk** [comment]
As I suspected. Unicorn/Rainbow mimics very closely how the built-in Sitecore serialization code behaves. Without looking deeper, I would say that the clone notifications likely rely on some kind of event being triggered. Both Unicorn and native, deserialization happens with events disabled.

I will give this a look when I get some time. But I propose you raise the vanilla issue with Sitecore Support. Whatever fix they give you, should likely solve the Unicorn behaviour as well.

**Comment by matthew0102** [comment]
Alright, I have raised a ticket to Sitecore support about this. Thank you for the help :)
