### ISSUE TITLE
Unicorn sync updates does not trigger clone notification

### ISSUE THREAD

**Issue by matthew0102** [SitecoreUnicorn/Unicorn#380]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Updating original items through Unicorn does not give change warning for cloned items

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create an item in Sitecore
2. Create a clone of the item in Sitecore
3. Serialize the original item in Unicorn
4. Update any field value of the cloned Item
5. Change the original item file outside your instance (ex. manually update yml file field value in notepad. This is to simulate switching of branch/deployment releases)
6. Sync the original item from Unicorn.aspx (this would change the value of the item)
7. Check the cloned item, it does not trigger a warning that the original item has changed (This causes the content editor to NOT be able to accept or reject the change that happened to the original item, it automatically rejects)

**What is the expected behavior?**
The cloned item should have triggered a warning notification that the original item has changed.
![image](https://user-images.githubusercontent.com/50011220/76285132-f10fef00-62d9-11ea-8dd8-4408aa2b1d67.png)

**Please mention your Sitecore version and Unicorn version.**
Sitecore 9 Update 2
Unicorn v4.0

I am re-creating this issue as the previous issue has been closed and a solution has not been made.
Link to the closed issue https://github.com/SitecoreUnicorn/Unicorn/issues/379

**Comment by matthew0102** [comment]
Any new news on this?

**Comment by cassidydotdk** [comment]
This is not a support portal. Don't open up multiple issues, it will not help in any way.

**Comment by matthew0102** [comment]
Alright, may I at least know which venue I can raise this issue?

**Comment by cassidydotdk** [comment]
In a Pull Request
