### ISSUE TITLE
Unicorn.Users not detecting includes in userPredicate

### ISSUE THREAD

**Issue by bcalisto-oshyn** [SitecoreUnicorn/Unicorn#386]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After installing the Unicorn.Users NuGet package in project and enabling the user sync configuration (custom, or the included Unicorn.Configs.Default.Users.config), the following YSOD error appears when trying to start Sitecore:

**No include entries were present on the predicate for the Default Configuration Unicorn configuration. You must explicitly specify the items you want to include.**

*Description:* An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

*Exception Details:* System.InvalidOperationException: No include entries were present on the predicate for the Oshyn.Web.Users Unicorn configuration. You must explicitly specify the items you want to include.

*Source Error:*

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

```
[InvalidOperationException: No include entries were present on the predicate for the Oshyn.Web.Users Unicorn configuration. You must explicitly specify the items you want to include.]
   Unicorn.Predicates.SerializationPresetPredicate.EnsureEntriesExist(String configurationName) +138
   Unicorn.Predicates.SerializationPresetPredicate..ctor(XmlNode configNode, IUnicornDataProviderConfiguration dataProviderConfiguration, IConfiguration configuration) +165
   lambda_method(Closure , Object[] ) +187
   Configy.Containers.MicroContainer.Activate(Type type, KeyValuePair`2[] unmappedConstructorParameters) +841
   System.Lazy`1.CreateValue() +243
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Lazy`1.get_Value() +14194460
   Configy.Containers.MicroContainer.Resolve(Type type) +59
   Configy.Containers.MicroContainer.Activate(Type type, KeyValuePair`2[] unmappedConstructorParameters) +405
   Configy.Containers.MicroContainer.Resolve() +110
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +145
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +498
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +90
   Unicorn.Data.DataProvider.UnicornSqlServerDataProvider..ctor(String connectionString) +222
```
**If the current behavior is a bug, please provide the steps to reproduce.**
Just install the Unicorn.Users NuGet package in your Sitecore project, enable the Unicorn.Configs.Default.Users.config.example file (or create a custom user sync config file), deploy and try to start the Sitecore instance, and you will get the YSOD.

**What is the expected behavior?**
User syncing should work.

**Please mention your Sitecore version and Unicorn version.**
Sitecore 9.3, using Unicorn 4.1.1

**Comment by kamsar** [comment]
Read the commented out but about user configurations that have no items :)

________________________________

**Comment by bcalisto-oshyn** [comment]
I enabled it, and I see that it needs class Unicorn.Roles.Predicates.EmptyPredicate from Unicorn.Roles. Shouldn't this library be fully independent? (in NuGet, it doesn't list Unicorn.Roles or Unicorn.Roles.Core as dependencies)
