### ISSUE TITLE
Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException

### ISSUE THREAD

**Issue by a3code** [SitecoreUnicorn/Unicorn#388]
Hello, I have a  dev git branch with some structure like /sitecore/content/my/MASTER/DEV/Data/Link Lists and dozen sub items under it.
at other git branch I moved all sub items to sitecore/content/my/MASTER/DEV/Data/My Link Lists ,  Link Lists is steel exist as well.
but when someone takes new branch and sync they got an error ParentItemNotFoundException: Exception of type 'Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException' was thrown. for all items that was moved.
but on second sync issue is gone. 
what could be a reason of it ?

**Comment by cassidydotdk** [comment]
One of your predicates rely on a root item that is not included in any of your configurations and/or is being synced in the wrong order. Use the `dependencies` attribute if it's the latter.
