### ISSUE TITLE
Child items in Unicorn placed in the Root folder with GUID name

### ISSUE THREAD

**Issue by LM-ARKAV** [SitecoreUnicorn/Unicorn#389]
I'm using Unicorn 4, and getting the below issue where my children items are placed with GUID as a folder name along with the Root folder. Do we have any fix for this?
 
![image](https://user-images.githubusercontent.com/57650497/86884744-99b64a00-c126-11ea-897a-2799e42aecb4.png)

**Comment by cassidydotdk** [comment]
This is by design. Unicorn will "wrap" a path when it becomes too long for the Windows filesystem (max 248 chars).

**Comment by LM-ARKAV** [comment]
> This is by design. Unicorn will "wrap" a path when it becomes too long for the Windows filesystem (max 248 chars).

Thanks for the clarification.
