### ISSUE TITLE
Unicorn Reserialize converting paths to lowercase 

### ISSUE THREAD

**Issue by kalyan9** [SitecoreUnicorn/Unicorn#392]
When doing a reserialize of an item (or tree), unicorn changes the path to lowercase of the third element from the root.

Ex: Original -> /sitecore/system/**S**ettings/Feature/
     New ->      /sitecore/system/**s**ettings/Feature/

Rainbow Version: 2.1.1

**Comment by cassidydotdk** [comment]
Share your config/predicate

**Comment by kalyan9** [comment]
Mark,
Here is the info from config/predicate as requested.

I am attaching the base configuration and also a specific feature config
too.
FYI..this is happening at all folder levels

Thanks,
Kalyan

<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/"
               xmlns:unicorn="http://www.sitecore.net/xmlconfig/unicorn/">
    <sitecore>
        <unicorn>
            <configurations>
                <configuration name="OneWeb.Feature"
                               abstract="true"
                               extends="OneWeb.Base"
                               dependencies="OneWeb.Foundation.*">
                    <predicate>
                        <include name="Templates" database="master"
path="/sitecore/templates/$(module)/COMPANYNAME/$(layer)/$(moduleConfigName)"
/>
                        <include name="Templates.Branches"
database="master"
path="/sitecore/templates/Branches/$(module)/COMPANYNAME/$(layer)/$(moduleConfigName)"
/>
                        <include name="System.Settings" database="master"
path="/sitecore/system/settings/$(module)/COMPANYNAME/$(layer)/$(moduleConfigName)"
/>
                        <include name="Layout.Renderings" database="master"
path="/sitecore/layout/Renderings/$(module)/COMPANYNAME/$(layer)/$(moduleConfigName)"
/>
                        <include name="Layout.PlaceholderSettings"
database="master" path="/sitecore/layout/Placeholder
Settings/$(module)/COMPANYNAME/$(layer)/$(moduleConfigName)" />
                        <include name="MediaLibrary" database="master"
path="/sitecore/media
library/$(module)/COMPANYNAME/$(layer)/$(moduleConfigName)" />
                    </predicate>
                </configuration>
            </configurations>
        </unicorn>
    </sitecore>
</configuration>


    <sitecore>
        <unicorn>
            <configurations>
                <configuration name="OneWeb.Feature.Insights"
                               extends="OneWeb.Feature"
                               dependencies="OneWeb.Foundation.*">
                    <predicate>

                    </predicate>
                </configuration>
            </configurations>
        </unicorn>
    </sitecore>




Thanks,
Kalyan

**Comment by cassidydotdk** [comment]
This still doesn't give me a coherent picture. I need a full reproducible set of configuration files and the corresponding directory tree that gets created.

I will say two things right now however.

1. There is not a single instance of `.ToLower` anywhere in the Unicorn/Rainbow codebase except for one which deals with configuration predicates. A feature you are not using, and it would not affect directory structure
2. Nor does it matter. Why do you care what case the directories get created in?

**Comment by kalyan9** [comment]
Just to clarify, this is happening only from unicorn dashboard (reserialize) not from the Sitecore (Serialize tree) option.

The reason it's an issue is we changed our serialization folder/tree structure to be aligned with Helix. After change, we did a reserialize and now we have thousands of changes just because of the lowercase path change.
Yes this should not affect any of the items however it's a big inconvenience to comb through all thousands of changes to make sure it's  only a case change.

**Comment by cassidydotdk** [comment]
Right, ok. But still. There is nothing in Unicorn that would mess with path casing. Directory names are derived from configuration names and if you issue a full Reserialize, the directory structure will get wiped and a new one put in place. Casing depending on those configuration names.

My guess would be, this could have something to do with those configuration variable replacers. But without an actual set of configs to reproduce the issue, I don't really have anything to go on.

Feel free to search through the entire codebase yourself for anything that would be lowercasing anything coming in from configuration.

**Comment by kalyan9** [comment]
Yes I noticed lowercase in the configuration but puzzled by the fact that Sitecore "serialize tree option" works fine but not from the unicorn dashboard.
I am in the process of fixing/verifying that with configuration changes and see if that changes anything.

Meanwhile I will send you all the configurations (need to mask few things) shortly.

**Comment by cassidydotdk** [comment]
That's because the command "Serialize Tree" works off an existing directory already in place. Without a root directory, a configuration could never become active and Serialize Tree could therefore never trigger.

But once it executes, the code is the same. Serialize Tree does not traverse a different codepath than normal serialization. 

Reserialize, however, will first wipe the root directory from existence and then proceed to build up the entire configuration again.

**Comment by kalyan9** [comment]
So I tried changing the case in configs as noticed before and that seems to have fixed, never imagined that would be the case :)

You below statement puts it correct:

"Directory names are derived from configuration names and if you issue a full Reserialize, the directory structure will get wiped and a new one put in place. Casing depending on those configuration names."

Thank you for the info, we will note it for future reference :)

**Comment by cassidydotdk** [comment]
You're welcome :)  Good luck.
