### ISSUE TITLE
Bug - Serialization Folder is being created in App_Data, regardless of config settings

### ISSUE THREAD

**Issue by Xalor90** [SitecoreUnicorn/Unicorn#395]
We are currently working on upgrading from Sitecore 8.2.7 to Sitecore 9.2 and are using Unicorn 4.1.1. We have a custom serialization folder in our solution and it is configured and works in Sitecore 8.2.7. However, in the upgraded project it does not seem to matter what location we set in the Unicorn config files, it always creates a new serialization folder under App_Data when we run Unicorn on the test server.

I have also noticed in testing locally that our v9 solution always creates a new serialization folder just outside the webroot, which is where we want it to be on the server, so it appears to be working correctly on my local environment. However, upon testing different locations, it appears the changes to the Unicorn configs have no effect locally either, as the Serialization always links back to the same location, regardless of the settings.

This is only occurring in our upgraded environments (locally and the test server) where we are using Sitecore 9.2.

**Comment by cassidydotdk** [comment]
Something else is different on your 9.2. I would guess you have old configs lying around still.  There are no changes in Unicorn behaviour nor the way the root folder is configured, on any 4.x Unicorn version.

Attach the full output of your showconfig.aspx if you want me to point the source of your problem out.
