### ISSUE TITLE
Unicorn 4.1.1 site definition breaks Horizon on Sitecore 10

### ISSUE THREAD

**Issue by whuu** [SitecoreUnicorn/Unicorn#398]
Unicorn adds new site definition defined in unicorn.config:
`<sites>
      
      <site name="unicorn"
				inherits="shell"
				enableItemLanguageFallback="false"
				enableFieldLanguageFallback="false"
				enforceVersionPresence="false"/>
    </sites>`

this definition is loaded by Horizon APIs to fetch list of sites and breaks whole editing. 
Most probably issue is caused by following call, which returns bad request:
`https://{my-sitecore-url}/sitecore/api/ssc/horizon/languages/?sc_horizon=api&sc_site=unicorn`

I guess the problem would be solved, if unicorn site wouldn't be returned by initial request to load list of sites:
`https://{my-sitecore-url}/sitecore/api/ssc/horizon/sites/-/getsites?sc_horizon=api&IncludeSystemSites=False`
if unicorn would be classified by this api as "system site".

**Comment by cassidydotdk** [comment]
Do you have a full stack trace and/or logs, from when this happens?

**Comment by cassidydotdk** [comment]
Actually,  never mind. `~\App_Config\Modules\Horizon\Sitecore.Horizon.Integration.config` has this configuration entry.

```
            <processor type="Sitecore.Horizon.Integration.Pipelines.ResolveHorizonMode.IgnoreBySiteName, Sitecore.Horizon.Integration" resolve="true">
              <ignoredSites hint="list:AddIgnoredSite">
                <shell>shell</shell>
                <login>login</login>
                <admin>admin</admin>
                <service>service</service>
                <modulesShell>modules_shell</modulesShell>
                <system>system</system>
                <publisher>publisher</publisher>
              </ignoredSites>
            </processor>
```

I don't have a full Horizon testing environment established right now, but can you please try and add `<unicorn>unicorn</unicorn>` to the list of ignored sites here, and confirm that this fixes the problem?

**Comment by cassidydotdk** [comment]
Additional info, the below class seems hardcoded in what it deems a "system site". If the above doesn't work, I guess this one needs to be patched.  Found in the `Sitecore.Horizon.Integration` assembly.

```
using Sitecore.Abstractions;
using Sitecore.Diagnostics;
using Sitecore.Horizon.Integration.Controllers.Data;
using Sitecore.Horizon.Integration.Controllers.Mapping;
using Sitecore.Horizon.Integration.ExternalProxy;
using Sitecore.IO;
using Sitecore.Sites;
using Sitecore.Web;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Sitecore.Horizon.Integration.Sites
{
  public class HorizonSiteManager : IHorizonSiteManager
  {
    private readonly HashSet<string> _systemSites = new HashSet<string>()
    {
      "shell",
      "login",
      "admin",
      "service",
      "modules_shell",
      "modules_shell",
      "modules_website",
      "scheduler",
      "system",
      "publisher",
      "exm"
    };
    private readonly BaseSiteContextFactory _siteСontextFactory;
    private readonly ISiteContextDtoMapper _mapper;
    private readonly ISitecoreContext _context;

    public HorizonSiteManager(
      BaseSiteContextFactory siteСontextFactory,
      ISitecoreContext context,
      ISiteContextDtoMapper mapper)
    {
      this._siteСontextFactory = siteСontextFactory;
      this._context = context ?? throw new ArgumentNullException(nameof (context));
      this._mapper = mapper ?? throw new ArgumentNullException(nameof (mapper));
    }

    public virtual SiteContextDto[] GetSiteByName(string name)
    {
      SiteContext siteContext = this._siteСontextFactory.GetSiteContext(name);
      if (siteContext == null)
        return (SiteContextDto[]) Array.Empty<SiteContextDto>();
      return new SiteContextDto[1]
      {
        this._mapper.Map(siteContext)
      };
    }

    public SiteContextDto TryBestMatchClientSiteByHost(string host)
    {
      Assert.ArgumentNotNullOrEmpty(host, nameof (host));
      SiteInfo info = this.GetAllSiteInfos(false).FirstOrDefault<SiteInfo>((Func<SiteInfo, bool>) (x => !string.IsNullOrEmpty(x.HostName) && x.Matches(host)));
      return info == null ? (SiteContextDto) null : this._mapper.Map(new SiteContext(info));
    }

    public IEnumerable<SiteContextDto> GetAllSites(bool includeSystemSites) => (IEnumerable<SiteContextDto>) this._mapper.Map(this.GetAllSiteInfos(includeSystemSites).Select<SiteInfo, SiteContext>((Func<SiteInfo, SiteContext>) (x => new SiteContext(x))));

    private IEnumerable<SiteInfo> GetAllSiteInfos(bool includeSystemSites)
    {
      IEnumerable<SiteInfo> source = (IEnumerable<SiteInfo>) this._siteСontextFactory.GetSites();
      if (!includeSystemSites)
        source = source.Where<SiteInfo>((Func<SiteInfo, bool>) (site => !this._systemSites.Contains(site.Name)));
      return source.Where<SiteInfo>((Func<SiteInfo, bool>) (site => this._context.Database.GetItem(FileUtil.MakePath(site.RootPath, site.StartItem)) != null));
    }
  }
}
```

**Comment by cassidydotdk** [comment]
Or possibly look into, forcing this expression to false. 

`site => this._context.Database.GetItem(FileUtil.MakePath(site.RootPath, site.StartItem)) != null)`

**Comment by whuu** [comment]
I tried with additional entry in `<ignoredSites hint="list:AddIgnoredSite">` configuration, but didn't solve the issue. 
As you stated, checking of "system sites" by horizon seems to be hardcoded. I will create ticket and ask sitecore support about that.

**Comment by cassidydotdk** [comment]
There is one more thing we can try. The `unicorn` site itself is only needed to ensure Unicorn does not get affected by all sorts of language fallback settings and whatever else. But it never "runs" as a site. Looking at the above, we could possibly force Horizon to ignore the site by giving it a dummy site root configuration.

Could you try adding this, to the Unicorn site definition?

`rootPath="/unicorn/module" startItem="/home"`

(which should return `null` from `.GetItem`)

So essentially changing Unicorn.config to this

```
		<sites>
			<!-- A controlled site context to run Unicorn sync processes in, where we know Language Fallback features and other misguidings are inactive -->
			<site name="unicorn"
				inherits="shell"
                                rootPath="/unicorn/module"
				enableItemLanguageFallback="false"
				enableFieldLanguageFallback="false"
				enforceVersionPresence="false" />
		</sites>
```

While not pretty, if this workaround works as I hope it will it seems the path of least resistance moving forward.

**Comment by whuu** [comment]
Yup, I tested with `rootPath="/unicorn/module"` and can confirm that this workaround works.

**Comment by cassidydotdk** [comment]
Perfect. I will get this worked into the upcoming release. There are no detrimental effects from this, as nothing but Unicorn itself should really be working in this Site Context anyway.

**Comment by cassidydotdk** [comment]
This has been pushed as 4.1.2-pre6 - https://github.com/SitecoreUnicorn/Unicorn/releases/tag/4.1.2-pre6

I expect to make a full release of 4.1.2 this weekend, which will not differ significantly from this release. It's mostly some supporting documentation I need to write and I lack the time just now.

Thanks for bringing this to my attention :-)

**Comment by nevnet** [comment]
Pretty sure this site definition should be limited to Standalone & ContentManagement. I get the error "Could not find base site 'shell' for site 'unicorn'" on Content Delivery servers because there is no 'shell' site on CDs.

**Comment by cassidydotdk** [comment]
True. But there isn't a single Unicorn configuration file that should be deployed to a CD server to begin with.
