### ISSUE TITLE
Unicorn & Synthesis - Is there a way to auto sync Sitecore Items

### ISSUE THREAD

**Issue by unstab1e** [SitecoreUnicorn/Unicorn#399]
I am currently working with St. Luke's Hospital, Boise, ID on their Sitecore 9.3 and 10.0 websites.

** THIS QUESTION IS NOT IN RELATION TO TRANSPARENT SYNC **

I may be wrong in this, but I recall in previous uses of Unicorn & Synthesis, that when Insert/Update/Delete items in Sitecore you configure the tools to automatically update their related files (Unicorn: .yml files ; Synthesis : Synthesis.Model.cs file) . No syncing or rebuilding necessary.

Am I wrong? If not what setting controls controls this in each tool?

Respond to tmgrable@gmail.com

**Comment by cassidydotdk** [comment]
That is still the case. For Unicorn, this functionality is provided by enabling the Data Provider.

https://github.com/SitecoreUnicorn/Unicorn/blob/master/src/Unicorn/Standard%20Config%20Files/Unicorn.DataProvider.config

Notice that by default, this is set to operate only in the `StandAlone` role - which would be the assumed default for a standard Developer workstation. Your setup might be in `ContentManagement` role, in which case you would need to add this role to this configuration.

Like `<sitecore role:require="Standalone or ContentManagement">`

Take care not to enable this on upstream environments however.

**Comment by blipson89** [comment]
Synthesis has a config file [Synthesis.AutoRegenerate.config](https://github.com/blipson89/Synthesis/blob/9.1.0.2/Source/Synthesis/Standard%20Config%20Files/Synthesis.AutoRegenerate.config). 

When that's present, the models should auto regenerate on save/deleted/moved/renamed.
