### ISSUE TITLE
sitecore stalls for 10-15 minutes on clean install

### ISSUE THREAD

**Issue by UffeHammer** [SitecoreUnicorn/Unicorn#403]
sitecore stalls for 10-15 minutes on clean install of our website using an azure deployment to a server, it seems that it has to rebuild our entire dictionary when unicorn sync is called, this dictionary contains 40.000 items so it takes a while to rebuild the dictionary.dat file in the data folder.
Is there anyway to disable a dictionary rebuild when syncing unicorn?

Sitecore version: 9.3.0
Unicorn version: 4.0.4

**Comment by cassidydotdk** [comment]
Unicorn doesn't have any code triggering a dictionary rebuild.

Also, update. 4.0.4 is way old.

**Comment by UffeHammer** [comment]
Nonetheless the dictionary is rebuilt when we do a unicorn sync, could this then be because we have unicorn items that are in the dictionary part of sitecore?


also our version of unicorn was 4.1.1

**Comment by cassidydotdk** [comment]
Could be, yes. I can't really tell since I don't know anything about your setup.

Also; specifically what do you mean by "dictionary rebuild"?   The dictionary isn't something one "rebuilds" as such. Unicorn or otherwise. What's in your logs?

**Comment by UffeHammer** [comment]
There is a dictionary.dat file in the temp folder that is set to size 0 and then slowly grows in size after a unicorn sync, and when it reaches the final size the site becomes responsive again, therefore i deduced that the file is being rebuilt :)

**Comment by UffeHammer** [comment]
The log only contains the standard message after unicorn sync:
WARN  All caches have been cleared. This can decrease performance considerably.

**Comment by cassidydotdk** [comment]
Right, but this is normal.

There are many ways to implement a dictionary cache refresh/rebuild. None of them come from Unicorn however. Take a look at this article, and that is just one example.

https://horizontal.blog/2017/11/25/troubleshooting-issues-with-sitecore-dictionary-in-multi-lingual-solutions/

Possibly someone implemented a publish:end handler in your solution that triggers this. I don't know.

**Comment by UffeHammer** [comment]
How about this one:
	/// <summary>
	/// Clears the dictionary if a dictionary entry was part of a sync
	/// </summary>
	public class DictionaryCacheClearer : IUnicornSyncCompleteProcessor
	{
		public void Process(UnicornSyncCompletePipelineArgs args)
		{
			var targetId = TemplateIDs.DictionaryEntry.Guid;

			if (args.Changes.Any(item => (item.TemplateId ?? Guid.Empty).Equals(targetId)))
			{
				var log = args.Configuration.Resolve<ILogger>();

				log.Debug(string.Empty);
				log.Debug("> Dictionary entries were altered during sync. Clearing dictionary caches...");
				Translate.ResetCache();
			}
		}
	}

**Comment by cassidydotdk** [comment]
Right, that would do it. But it triggers when dictionary items have been updated. If you don't clear the caches your changes will never see the light of day. Disable it if you're fine with this - I just don't see what good that would do.

Am actually curious; how do you end up with a solution that has 40k dictionary entries anyway? :P   you are aware items can have fields and fields can have values? ;-)

**Comment by UffeHammer** [comment]
The big dictionary is because one of the developers is using the dictionary for generalized words and sentences, so we installed sitecores own dictionary in the core database and that is 40k items and already preinstalled in english (so you can ask them about fields and values).
That worked fine when sitecore could read from the core database on the CD frontend servers but now they have closed access to the core database from the CD servers, so we could not read the dictionary anymore on the CD servers and the only solution was to install it on the master database instead.

But i will be making a script to remove the dictionary and only install the items in the dictionary that we are actually using.

Even if i could remove UNICORN'S dictionary clearing then we would still have a lot of extra items that are unnessesary.

**Comment by cassidydotdk** [comment]
Haha there are some funny things you can do with Sitecore's built in client translation dictionary, but I'll leave that for another day ;-)

Anyway first things first. That dictionary clearer in Unicorn is controlled by Unicorn.config. You can do a patch:delete to get rid of it if you want. 

https://github.com/SitecoreUnicorn/Unicorn/blob/d9c601cffc8aeae1ae1ecaf03527b88c66f42b85/src/Unicorn/Standard%20Config%20Files/Unicorn.config#L191

As I said though, you will then need to come up with another way of rebuilding the dictionary cache.

**Comment by UffeHammer** [comment]
Thanks, but i have deleted the items from sitecores language package, and removed unicorn control of any dictionary items.
Finally i have disabled DictionaryCacheClearer but i can see that the dictionary is still rebuilt when i do a Unicorn sync??

It goes a lot faster now, but i'm baffled how it can still rebuild the dictionary.

**Comment by cassidydotdk** [comment]
Well if you're sure you removed that config entry, there would be nothing (in Unicorn) to trigger it.

You certain you patched it out?  not just delete it directly in the unicorn.config file?  that one might get redeployed over and over in most build processes.
