### ISSUE TITLE
No include entries were present on the predicate for the I Have a Custom Storage Path Unicorn configuration. You must explicitly specify the items you want to include.

### ISSUE THREAD

**Issue by dbalosetti** [SitecoreUnicorn/Unicorn#405]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
On a clean unicorn installation on Sitecore 9.3 when i try to access to the site i get No include entries were present on the predicate for the I Have a Custom Storage Path Unicorn configuration. You must explicitly specify the items you want to include.

System.InvalidOperationException: No include entries were present on the predicate for the I Have a Custom Storage Path Unicorn configuration. You must explicitly specify the items you want to include.

```
[InvalidOperationException: No include entries were present on the predicate for the I Have a Custom Storage Path Unicorn configuration. You must explicitly specify the items you want to include.]
   Unicorn.Predicates.SerializationPresetPredicate.EnsureEntriesExist(String configurationName) +138
   Unicorn.Predicates.SerializationPresetPredicate..ctor(XmlNode configNode, IUnicornDataProviderConfiguration dataProviderConfiguration, IConfiguration configuration) +210
   lambda_method(Closure , Object[] ) +187
   Configy.Containers.MicroContainer.Activate(Type type, KeyValuePair`2[] unmappedConstructorParameters) +841
   System.Lazy`1.CreateValue() +243
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Lazy`1.get_Value() +14194428
   Configy.Containers.MicroContainer.Resolve(Type type) +59
   Configy.Containers.MicroContainer.Activate(Type type, KeyValuePair`2[] unmappedConstructorParameters) +405
   Configy.Containers.MicroContainer.Resolve() +110
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +145
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +498
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +90
   Unicorn.Data.DataProvider.UnicornSqlServerDataProvider..ctor(String connectionString) +222

[TargetInvocationException: Eccezione generata dalla destinazione di una chiamata.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +223
   Sitecore.Reflection.ReflectionUtil.CreateObject(Type type, Object[] parameters) +119
   Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +108
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +163
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72
   Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert) +703
   Sitecore.Configuration.DefaultFactory.CreateFromReference(XmlNode configNode, String[] parameters, Boolean assert) +170
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +116
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72
   Sitecore.Configuration.DefaultFactory.GetInnerObject(XmlNode paramNode, String[] parameters, Boolean assert) +947
   Sitecore.Configuration.DefaultFactory.AssignProperties(XmlNode configNode, String[] parameters, Object obj, Boolean assert, Boolean deferred, IFactoryHelper helper) +545
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +326
   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72
   Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert) +703
   Sitecore.Configuration.DefaultFactory.GetDatabase(String name, Boolean assert) +157
   Sitecore.Configuration.DefaultFactory.GetDatabase(String name) +55
   Sitecore.Configuration.DefaultFactory.GetDatabases() +121
   Sitecore.Data.Managers.DefaultItemManager.Initialize() +101
   (Object , Object ) +60
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +490
   (Object , Object ) +9
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +490
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +236
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22
   Sitecore.Nexus.Web.HttpModule.Application_Start() +220
   Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +1145
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +584
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369

[HttpException (0x80004005): Eccezione generata dalla destinazione di una chiamata.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +724
```

**If the current behavior is a bug, please provide the steps to reproduce.**
try to call the website
**What is the expected behavior?**
see the website/sitecore and unicorn page
**Please mention your Sitecore version and Unicorn version.**
Sitecore 9.3 Unicorn 4.1.3

**Comment by cassidydotdk** [comment]
As the message says; you must actually define a configuration for it before it can do anything. You can make a copy of https://github.com/SitecoreUnicorn/Unicorn/blob/master/src/Unicorn/Standard%20Config%20Files/Unicorn.Configs.Default.example as your starting point.

**Comment by dbalosetti** [comment]
Hi Mark,
i have set the Unicorn.Configs.Default.config under app_config with just a predicate to test it:

`
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/" xmlns:role="http://www.sitecore.net/xmlconfig/role/">
	<sitecore>
		<unicorn>
			<configurations>
				
				<configuration name="Feature.Sample" description="Write something here about why this configuration exists and what it's for. Or remove the attribute; it's optional.">
					<predicate>
						
						<include name="Layouts" database="master" path="/sitecore/layout/Layouts" />
						
					</predicate>

					
					<predicate fieldTransforms=";Title,:Text,!Include In Sitemap,+Api Endpoint[{$apiEndPoint$}],?Default Product">
						<include name="Sample Data" database="master" path="/sitecore/content/global/sample" fieldTransforms="-Title" /> /* Predicate transforms apply, but "Title" gets ignored on this include definition */
					</predicate>


					
					<predicate>
						<include role:require="Standalone" name="Sample Data" database="master" path="/sitecore/content/global/sample" fieldTransforms="!Workflow,!Workflow State" />
						<include role:require="ContentManagement" name="Sample Data" database="master" path="/sitecore/content/global/sample" fieldTransforms="+Workflow[{2DE02B52-B95F-404A-A955-C36B290F1B57}],+Workflow State[{5ACE9C7F-8A18-4C77-BC30-03BE5A40E6B6}]"/>
					</predicate>

					
					<dataProviderConfiguration enableTransparentSync="false" />

					
					<syncConfiguration updateLinkDatabase="false" updateSearchIndex="false" />
				</configuration>
			</configurations>
		</unicorn>
	</sitecore>
</configuration>
`

**Comment by cassidydotdk** [comment]
You can't just enable the example config with no changes and expect it to work. 

- Create a folder under App_Config/Include, name it `z.Unicorn`.
- Paste the below into a file you name Sample.config
- Get rid of your Unicorn.Configs.Default.config

```
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/" xmlns:role="http://www.sitecore.net/xmlconfig/role/">
	<sitecore>
		<unicorn>
			<configurations>
				<configuration name="Sample" description="Write something here about why this configuration exists and what it's for. Or remove the attribute; it's optional.">
					<predicate>
                        <include name="Sample.Content" database="master" path="/sitecore/content/home" />
					</predicate>
				</configuration>
			</configurations>
		</unicorn>
	</sitecore>
</configuration>
```

**Comment by dbalosetti** [comment]
Same exception, i've already tried differents configuration with no luck.. in attached include folder
[App_Config_Include.zip](https://github.com/SitecoreUnicorn/Unicorn/files/5843596/App_Config_Include.zip)

**Comment by cassidydotdk** [comment]
You have renamed `Unicorn.CustomSerializationFolder.config.example` to `Unicorn.CustomSerializationFolder.config` and left it default. This file holds a number of examples of how you can configure different folders, but you cannot just enable it and leave them all in place.

Remove it.

**Comment by dbalosetti** [comment]
perfect thanks as lot!
