### ISSUE TITLE
Field __Revision - Reset to standard value - All fields synced

### ISSUE THREAD

**Issue by robmaas** [SitecoreUnicorn/Unicorn#412]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When syncing Unicorn, on some environments (not all of them) Unicorn fails to determine changes.
Each serialized item (we have a couple of thousands) is marked as an update based on the '__Revision' field and will get synced/published.
This results in syncs that take almost ten minutes, depending on environment.

Every item shows a warning like this (also different language versions for some items that have different language versions):
`Field __Revision - en#1 - Reset to standard value`

**If the current behavior is a bug, please provide the steps to reproduce.**
Sync Unicorn.
Sometimes reserializing after a deploy seems to fix the issue for a while, but the issue comes back after a couple of deployments.

**What is the expected behavior?**
Revision field should not be a field that causes a change-flag.

**Please mention your Sitecore version and Unicorn version.**
Sitecore version 9.2 IR
Unicorn 4.1.4

The issue seems similar to this one: https://sitecore.stackexchange.com/questions/9671/unicorn-always-serializes-items-which-have-fallback-enabled
However we experience the issue on both 4.1.1 and 4.1.4.

**Comment by cassidydotdk** [comment]
What is the ShowConfig.aspx output for your field filters?  __Revision is exluded by default.

https://github.com/SitecoreUnicorn/Unicorn/blob/8716fe4ddb0d14165d222cebaae56dad41992805/src/Unicorn/Standard%20Config%20Files/Unicorn.config#L110

**Comment by cassidydotdk** [comment]
And since it doesn't happen consistently for you; likely one of your team members is serializing content based on a different configuration than the rest of you. Use git to trace this down.

**Comment by robmaas** [comment]
@cassidydotdk Thanks for pointing me to that direction. Looks like someone in my team created a patch to exclude a specific field on specific environments. The patch completely replaces the default ConfigurationFieldFilter config section, and therefore the default excluded fields 😓 
Apologies for bothering you with this. Will close this one, I'm sure fixing the patch will resolve the "issue".

**Comment by cassidydotdk** [comment]
Ah, the joys of rogue configurations :D     While checking this, make sure _everyone_ on the is using the _exact_ same Rainbow.config. Sometimes developers think they can "just adjust these path lengths locally" because of their local folder structure or whatever. And it will lead to _really nasty_ problems later on, if this configuration is not the same everywhere. On every environment.

https://github.com/SitecoreUnicorn/Rainbow/blob/master/src/Rainbow/Rainbow.config
