### ISSUE TITLE
Error message during Unicorn Sync "The statement terminated. The maximum recursion 100 has been exhausted before statement completion."

### ISSUE THREAD

**Issue by gkbalaji03** [SitecoreUnicorn/Unicorn#424]
Hi Unicorn Team,

We had faced the issue mentioned in the title during Unicron Sync and the details of the issue are mentioned below.

**Do you want to request a *feature* or report a *bug*?**
I want to report a bug in the existing Unicorn feature

**What is the current behavior?**
We have many projects set up and the number of Sitecore items grows and has grown-up over the period of time. We use Unicorn Sync in our project to serialize the Sitecore items. And we noticed the below-mentioned error very recently which is happening when we run the Unicorn Sync task.
_**The statement terminated. The maximum recursion 100 has been exhausted before statement completion.**_

We did some analysis on our own in the first place to understand the root cause of the issue.
1. We have a serialization config as below that has a parent item (parent site umbrella for all the projects) with a include entry under which there are a group of exclude entries.
`<sitecore ...>
    <unicorn>
      <configurations>
        <configuration name="a.b" description="Site" dependencies="..." extends="...">
          <predicate>
            <include name="ParentSite.Content" database=".." path="/sitecore/content/ParentSite">
              <exclude childrenOfPath="/sitecore/content/ParentSite/x/y"/>
              <exclude childrenOfPath="/sitecore/content/ParentSite/a/b"/>
              <exclude childrenOfPath="/sitecore/content/ParentSite/c/d" />
			  .
			  .
			  .
			  </include>`

2. One thing we did to see if the error doesn't come up was commenting out the entire include and exclude entry and noticed that it doesn't display the same error.

3. When we searched through the background of the issue we understood that it is related to the SQL CTE and noticed that the query being used in the **SQLPreCacheStore.cs** may need the **OPTION(MAXRECURSION _limit_)** to mitigate the recursion error.

4. We ran the below query with the OPTION parameter as a standalone SQL Query in our environment which is giving the issue and noticed it did not produce the error. For your quick reference
```
;WITH Roots AS (
					SELECT Id
					FROM Items
					WHERE ID {rootItemIdsInStatement}
				), tree AS (
					SELECT x.ID, x.Name, x.TemplateID, x.MasterID, x.ParentID
					FROM Items x
					INNER JOIN Roots ON x.ID = Roots.ID
					UNION ALL
					SELECT y.ID, y.Name, y.TemplateID, y.MasterID, y.ParentID
					FROM Items y
					INNER JOIN tree t ON y.ParentID = t.ID
				)
				INSERT INTO #TempItemData
				SELECT *
				FROM tree
				OPTION(MAXRECURSION <a number limit>)
				SELECT ID, Name, TemplateID, MasterID, ParentID
				FROM #TempItemData
```

**If the current behavior is a bug, please provide the steps to reproduce.**
We feel the current behavior is a bug, and have mentioned the steps above and the fix we identified for it. What will be the possible solution for this issue and how can we integrate the solution into our environment?

**What is the expected behavior?**
Mentioned above is the issue that should be mitigated.

**Please mention your Sitecore version and Unicorn version.**
**Sitecore.NET 9.0.0 (rev. 171002)**
**Unicorn Version - 4.0.3**

Regards,
Balaji

**Comment by cassidydotdk** [comment]
Is Dilithium active on the affected projects?  And if so, does disabling it make any difference?

**Comment by gkbalaji03** [comment]
Hi @cassidydotdk ,

Thanks for reaching out immediately! In the meantime, we had identified the actual root cause of the issue and there was a content item structure that was causing the max recursion error. Sorry for the confusion.

We are good now and I am closing this thread.

Regards,
Balaji
