### ISSUE TITLE
Unicorn RainbowCodeGeneration is not supporting Sitecore 10.2 for serializing model

### ISSUE THREAD

**Issue by SarthakGupta20** [SitecoreUnicorn/Unicorn#432]
We are upgrading Sitecore 9.2 to Sitecore 10.2, earlier we used Unicorn and RainbowCodeGeneration, which used to work fine. During upgrade to Sitecore 10.2, we upgraded the Sitecore.Kernal version and below dlls

Sitecore.Kernel – 10.2
Sitecore.Logging – 10.2
Microsoft.Extensions.DependencyInjection.Abstractions - 3.1.14
Microsoft.Extensions.DependencyInjection - 3.1.14
Rainbow.Core - 2.1.4
Rainbow.Storage.Yaml - 2.1.4
RainbowCodeGeneration - 0.3.0
So now when we are trying to generate code using .tt file, it throws error(PFA):

Failing at:RainbowCodeGeneration.RainbowReader.GetTemplates(Host.ResolvePath(physicalFileStore), treeName, treePath); Attaching .tt file for the reference.

It seems that the version RainbowCodeGenaration refers is not supported by Sitecore.Kernal(10.2). So there seems an ambiguity between these versions.

Exception: Running transformation: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=' or one of its dependencies. The system cannot find the file specified.

So I want to know which version of Rainbow assemblies can support similar code generation feature with Sitecore 10.2 as I am getting exceptions

I could see a similar issue was raised for Sitecore 9.x but there is nothing mentioned about Sitecore 10.2

I wanted to know does Unicorn support Sitecore 10.2 version or not.

**Comment by cassidydotdk** [comment]
Yes

**Comment by SarthakGupta20** [comment]
Do you have any idea about above issue?

**Comment by cassidydotdk** [comment]
No. You need to take it up with the author of RainbowCodeGeneration. https://github.com/heikof/RainbowCodeGeneration
